### ISSUE TITLE
Has anyone been able to run this on macOS?

### ISSUE THREAD

**Issue by almeath** [sarah-walker-pcem/pcem#110]
Has anyone been able to get this to compile and run in macOS? 

I was able to successfully compile this in Mojave (10.14.6) with no errors, and everything works fine up to the point of starting a virtual machine. 

The configuratator works, but no matter what BIOS I select, PCem crashes out within about half a second of starting the virtual machine. Sometimes the first few lines of BIOS text can be seen before the window closes, but there is no crash report or other error message being generated by macOS.

I looked in the Terminal, and the only output is:

Item not found 1403
Item not found 1404

I have not tested this in macOS Monterery, but will try to do so soon.

**Comment by michael-manley** [comment]
Closing Ref #131
