### ISSUE TITLE
Can't get Windows 95 networking to work

### ISSUE THREAD

**Issue by AnthonyRyuki** [sarah-walker-pcem/pcem#113]
**Describe the bug**
Whenever I start Windows 95 with any network card and the appropriate driver installed, the following error message will show: "This DHCP client was unable to obtain an IP network address from a DHCP server." Because of that, I can't get connected to the Internet even if I install TCP/IP into the Network settings.
Also, the message will show up again after some time.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Network' and choose any network card
3. Install Windows 95 and make sure the appropriate drivers for that network card are installed

**Expected behavior**
The described error message shouldn't pop up and I should be able to get connected to the Internet.

**Screenshots**
![Screenshot from 2022-02-08 22-35-51](https://user-images.githubusercontent.com/62845774/153079982-af42758d-85d5-4613-8d9e-32abdbfd1842.png)
![Screenshot from 2022-02-08 22-36-05](https://user-images.githubusercontent.com/62845774/153079987-eae834e5-639e-48da-9db6-b6104f3cbefc.png)
![Screenshot from 2022-02-08 22-36-21](https://user-images.githubusercontent.com/62845774/153079989-c47406b2-7a80-4b2c-9dc1-ce3ac78d2c50.png)

**Emulator configuration**
 - Machine: [Socket 7] Shuttle HOT-557
 - CPU: Intel Mobile Pentium MMX 166
 - Graphics/sound cards: ATI Graphics Pro Turbo (Mach64 GX), Sound Blaster AWE32
 - Installed OS: Windows 95

**Host machine**
 - OS: Windows 10
 - PCem ver17

**Additional context**
Nothing to add.

**Comment by lautis0503** [comment]
This is probably not a bug of PCem.
The following is mine.

Machine: [Socket 7] Shuttle HOT-557
CPU: Intel Pentium 133
Graphic: Tseng ET4000Ax
Sound: Sound Blaster 16
Network: Novel NE2000 (address: 0x300, IRQ 10)
Installed OS: Windows 95

Host: Windows 7, PCem v17
Network type: PCAP

Everything works fine.
One suggestion: check your network driver address and IRQ in Windows 95.

**Comment by lautis0503** [comment]
Screenshots:
![Screenshot from 2022-02-18 23-37-08](https://user-images.githubusercontent.com/16025671/154713782-ba4ec020-7143-486e-8bd9-ba1b247b602a.png)

**Comment by AnthonyRyuki** [comment]
I'll give it a shot, though this issue also affects the Realtek card, whose parameters can't be configured.

**Comment by ruben-balea** [comment]
For the Realtek card I tried under Windows 95 OSR 2 Build 4.00.1111 these three drivers from: [https://www.realtek.com/en/component/zoo/category/rtl8029as-software](url)

RTL8029.SYS version: 3.29.98.0514 
Installed using inf file from zip archive 0001-oem-8029(355).zip [\\]
Download description: "OEM disk for users and manufacturers"
Test completed successfully

RTL8029.SYS version:  3.29.98.0724
Installed using inf file from zip archive 0001-win95-8029(506).zip [\WIN95\WIN95A]
Download description: "Windows 95"
Test completed successfully

RTL8029.SYS version: 5.505.0106.2000
Installed using inf file from zip archive 0001-win95-8029(506).zip [\WIN95]
Download description: "Windows 95"
Test completed successfully

The test was simply doing a Google search using Internet Explorer 3 included with that version of Windows, more than enough to verify that DHCP was working properly.
There are probably differences in reliability, stability, performance, etc. between the different driver versions but that is not something that I can test.

**Comment by AnthonyRyuki** [comment]
I've just reinstalled the Realtek driver after installing the Voodoo driver. Looks like that took care of some hardware conflict, in fact it's working now. Thanks for the help!
