### ISSUE TITLE
Mouse is not released with Ctrl + End in dev (vNext) build

### ISSUE THREAD

**Issue by eddlang** [sarah-walker-pcem/pcem#118]
It works on v17 but not on vNext (at least not in build 19051875)

**To Reproduce**
Simply press Ctrl + End.

**Expected behavior**
Mouse should be released.

**Emulator configuration**
 - Machine: ASUS P55T2P4
 - CPU: Pentium MMX 200
 - Graphics/sound cards: Voodoo 3 2000  / Sound Blaster 16
 - Windows 98 SE

**Host machine**
 - OS: Windows 10
 - vNext 19051875 (32-bit)

**Additional context**
This is the pre-compiled build I downloaded from the Actions section.

**Comment by michael-manley** [comment]
This issue looks similar to #89.

The fix for that only affected the SDL code for Linux/macOS. Ill add the same fix for Windows
