### ISSUE TITLE
VGA bug : Titan game

### ISSUE THREAD

**Issue by Altheos** [sarah-walker-pcem/pcem#12]
**Describe the bug**
There's a rendering error using any VGA graphic card and the game Titan (from Titus).
The bottom of the screen  during game is not rendered correctly and scroll is not smooth.
Game is probably using a VGA register trick as EGA rendering seems to be good.

**To Reproduce**
1. Run Titan.com
2. Start a game
3. Observe visual issue

**Expected behavior**
smooth scroll and no glitches

**Screenshots**
![Titan VGA Bug_2](https://user-images.githubusercontent.com/29195397/118780919-d4335c00-b88c-11eb-83f1-e0c642f8f67a.JPG)

**Emulator configuration**
 - Machine: AMI WinBIOS 486
 - CPU: Intel 486DX4 100
 - Graphics/sound cards: VGA
 - Installed OS : MSDOS 5

**Host machine**
 - OS: Windows 10
 - Emulator version : v17

**Comment by sarah-walker-pcem** [comment]
Titan clears bit 0 of CRTC register 0x17 (map row bit 0 to memory address bit 13 - used for CGA compatibility) to force a 32k wraparound. Interesting technique, should be implemented as part of a general update of VGA addressing.

**Comment by sarah-walker-pcem** [comment]
Fixed in commit 092be3e9.

**Comment by Altheos** [comment]
Thanks !
