### ISSUE TITLE
Possibly switching to Meson for v18

### ISSUE THREAD

**Issue by michael-manley** [sarah-walker-pcem/pcem#122]
As Currently I am developing in Windows, I have been noticing some major issues with CMake overall. I have to use MSYS bash console to even get it to detect wxWidgets, this is basically the dealbreaker, I cant use any IDE's properly.

I also don't want to force people to use MSYS, there are some edge cases where they might want to use their older GCC with maintained libraries to compile PCem

CMake will stay in there and maintained alongside Meson least till I feel it is matured enough to replace CMake.

I hate changing build systems again but better early on then later

**Comment by shermp** [comment]
If you need any assistance on the Windows side, I'm happy to help.

Not quite sure how you're going to handle dependency resolution in non msys2 or vcpkg environments though. Meson is pretty tied up with pkg-config (or CMake as a fallback). I guess there's always the wrapdb I suppose...

**Comment by michael-manley** [comment]
MinGW standalone does include pkg-config

The fun one is still wx-config, but Meson does work with a exe wrapper I designed to work with the shelled wx-config. Just requires a few things from MSYS that can be standalone. CMake no matter what would bomb out if it wasn't ran in MSYS

Plus Meson did clean up some code issues I had to make really bad hackjobs to get around (for instance CPU Type to build for)

And well I already was going to recommend Ninja so why not use the build system designed for Ninja :)

**Comment by shermp** [comment]
Meson certainly has one big advantage over CMake, extremely helpful developers who are happy to lend a helping hand where needed.

Rumor has it, if you chant _Meson_ three times, an @eli-schwartz will appear to offer guidance 😁 Seriously though, thank you.

**Comment by michael-manley** [comment]
[wx-config.zip](https://github.com/sarah-walker-pcem/pcem/files/8096318/wx-config.zip)
Attached to this is the wx-config.exe you can drop into c:/msys2/mingw32/bin or c:/msys2/mingw64/bin so that Meson can use the MSYS's wx-config in a normal windows command line. This helps IDE's better support wxWidgets

It is written in .NET 2.0 so it can support basically any version of Windows (starting from 98 basically)

**Comment by michael-manley** [comment]
Added a new [wx-config.zip](https://github.com/sarah-walker-pcem/pcem/files/8099407/wx-config.zip) as I seen something pretty crazy

Somehow wx-config --cflags has -fpermissive added to it but --cppflags (what everything is based off of) doesnt
![image](https://user-images.githubusercontent.com/291225/154738026-70f51198-10f0-43c7-a8b6-f268172b3eb1.png)
this is not valid for a C compiler, and it throws tons of errors about it only being for C++/ObjC

Reason we don't see this on CMake is CMake don't even put in CFLAGS, just CXXFLAGS, but Meson does.

So to work around this issue, I just in my utility replace --cflags to --cppflags before passing on to wx-config proper.

I should port this to C/C++ instead of C# but it was a quick way to do it for now.

Also here is the source if you want to build your own

```
using System;
using System.Diagnostics;
using System.IO;
using System.Reflection;

namespace wx_config
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var exeDirectory = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            Environment.SetEnvironmentVariable("PATH", Path.GetFullPath(Path.Combine(exeDirectory, "..\\..\\usr\\bin")) + ";" + Environment.GetEnvironmentVariable("PATH"));
            Environment.SetEnvironmentVariable("MSYSTEM", "MINGW32"); // This is to get correct paths from wx-config. This works fine even for MinGW64 mode

            var cmdline = "";

            if(args.Length > 0)
            {
                cmdline = Environment.CommandLine.Substring(Environment.CommandLine.IndexOf(args[0]));

                //FIX: To fix a weird issue with --cflags, going to actually change it to --cppflags in here to remove the MSYS -fpermissive tag
                cmdline = cmdline.Replace("--cflags", "--cppflags");
            }

            var p = new Process
            {
                StartInfo = new ProcessStartInfo(@"sh", Path.Combine(exeDirectory, "wx-config") + " " + cmdline)
                {
                    UseShellExecute = false
                }
            };

            p.Start();
            p.WaitForExit();
        }
    }
}
```

**Comment by michael-manley** [comment]
Nevermind, looks like its a Meson bug, its appending cxxflags to C, causing the error. Going to see if i can find a workaround

**Comment by shermp** [comment]
I wonder if you explicitly need to add `cxx = meson.get_compiler('cpp')` as well for meson to do the right thing here?

**Comment by eli-schwartz** [comment]
No, that just gives you a handle to the existing C++ compiler.

@michael-manley if wx-config has that in its cflags (and thus exposes it as the `dependency('wxwidgets')` compile options) then it seems like a legitimate upstream bug.

Do you have C code that builds with a C compiler and does not need wxwidgets, but is getting the wxwidgets compile options anyway? It seems like the simplest solution there would be to have that C code build as its own `static_library('foo_internal', ..., install: false)` with reduced dependencies. Then simply link this convenience library into the rest of the program.

**Comment by eli-schwartz** [comment]
Side note: requiring `-fpermissive` as a public header interface seems kind of... terrible? Why does wxwidgets do this?

**Comment by michael-manley** [comment]
So far I been peeking at the Meson source code and found this in the dependency logic
```
        # wx-config seems to have a cflags as well but since it requires C++,
        # this should be good, at least for now.
        self.compile_args = self.get_config_value(['--cxxflags'] + extra_args + self.requested_modules, 'compile_args')
        self.link_args = self.get_config_value(['--libs'] + extra_args + self.requested_modules, 'link_args')
```

Not very knowledgeable on the inner workings, but it seems self.compile_args gets appended to both c and cpp flags.

@eli-schwartz There is lots of source code in the wx-ui part that uses a wrapper to wrap the C++ code to be used in C. So I don't know if it be easy to wrap that in a static library. Really if there was a way to not append these flags in both c and cpp that would be the major fix, as CMake actually doesn't even append C's flags at all.

**Comment by michael-manley** [comment]
Note on myself: wxWidgets can seriously drive me nuts, but what other options is there. Qt is just too bloated for this project and this gives decent cross-compatibility lol.

**Comment by sjnewbury** [comment]
CPPFLAGS and CPP are for the "C Pre-Processor" flags and executable, not C++.   It's where defines and include paths go "-f" options do not belong there.  CXX* is for C++.

**Comment by michael-manley** [comment]
Learned CMakes issue was due to MSYS not being in the path. I might maintain these as an alternative, but CMake will stay the active primary build system for now.
