### ISSUE TITLE
Recommended Release Flags

### ISSUE THREAD

**Issue by michael-manley** [sarah-walker-pcem/pcem#123]
What is the build flags used on actual release builds. I would like to add that to the build system so when I'm ready for a release build all I need to do is specify as such.

**Comment by sarah-walker-pcem** [comment]
IIRC basic flags were as in Makefile.mingw-wx-sdl2 : 
`-O3 -march=i686 -fomit-frame-pointer -msse2 -mstackrealign -Werror -fno-strict-aliasing`

I also used profiling optimisations to eek a bit more performance from the release builds. Compile and link with "-fprofile-generate", run for a bit with a range of content, then recompile and relink with "-fprofile-use".
