### ISSUE TITLE
CGA bug : prohibition game

### ISSUE THREAD

**Issue by Altheos** [sarah-walker-pcem/pcem#13]
**Describe the bug**
There's a rendering error using CGA graphic card and the game Prohibition (Infogrames).
This game is using a CGA trick to do smooth scroll but screen is corrupted using Pcem.
Screen corruption is easily observable on start screen.

**To Reproduce**
1. Run prohi
2. Launch game choosing "Other" as video adapter and slow or high as speed
3. Launch game using spacebar then see error

**Expected behavior**
smooth scroll and no glitches

**Screenshots**
![Prohibiton CGA](https://user-images.githubusercontent.com/29195397/118805311-1321db80-b8a6-11eb-9f8d-99e61ff53a84.JPG)

**Emulator configuration**
 - Machine: AMI 286 Clone
 - CPU: Intel 286 10 Mhz
 - Graphics/sound cards: CGA
 - Installed OS : PCDOS 6.1 

**Host machine**
 - OS: Windows 10
 - Emulator version : v17

**Comment by sarah-walker-pcem** [comment]
Accesses CRTC at ports 3d0/3d1 instead of 3d4/3d5. Works on real hardware due to incomplete address decode.

**Comment by sarah-walker-pcem** [comment]
Fixed in c82cd20.

**Comment by Altheos** [comment]
Thanks for the fix.
