### ISSUE TITLE
V18 Release Plan

### ISSUE THREAD

**Issue by michael-manley** [sarah-walker-pcem/pcem#132]
I am getting ready for releasing a v18 so other then plugin system i am feature freezing for now. Been 2 years since a release :)

I am looking into the dynarec issues and also the issues with Linux being broken (segfaults). I think fixing the headers might fix a bit of these issues.

**Comment by JimboMumbo** [comment]
I'm pretty sure there are new drivers coming together in this build.

**Comment by michael-manley** [comment]
So the plan now is SDL Separation from WxWidgets, Going Qt, and then Dynarec bug fixes.

Dynarec is a major blocking bug and is the real reason a v18 hasn't really been on the horizon. Hopefully, if everything goes well, give 3 months for a v18.

**Comment by JimboMumbo** [comment]
3 months would be worth it

**Comment by KoghaandSooga** [comment]
> So the plan now is SDL Separation from WxWidgets, Going Qt, and then Dynarec bug fixes.
> 
> Dynarec is a major blocking bug and is the real reason a v18 hasn't really been on the horizon. Hopefully, if everything goes well, give 3 months for a v18.

Thanks for the estimate.  It's rare a dev cares enough to understand fans need a general estimate.
