### ISSUE TITLE
[git] Cannot build pcem from git: Could NOT find wxWidgets

### ISSUE THREAD

**Issue by FredBezies** [sarah-walker-pcem/pcem#133]
**Describe the bug**
Hello.

I'm trying to build pcem using git code and after migrating from meson to cmake on Archlinux.

Here is my cmake line: 

`cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DUSE_NETWORKING=ON -DUSE_PCAP_NETWORKING=ON -DUSE_ALSA=ON -DPLUGIN_ENGINE=ON ..`

**To Reproduce**

1. Grab latest git code
2. Use cmake line from details
3. Wait a little...

**Expected behavior**
Build process going on.

Error log:

```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindwxWidgets.cmake:1025 (find_package_handle_standard_args)
  CMakeLists.txt:114 (find_package)
```

**Comment by michael-manley** [comment]
Is this package installed? https://archlinux.org/packages/extra/x86_64/wxgtk3/

**Comment by FredBezies** [comment]
> Is this package installed? https://archlinux.org/packages/extra/x86_64/wxgtk3/

Yes.

```
pacman -Qi wxgtk3 | grep Installed
Installed Size  : 15,08 MiB
Install Reason  : Installed as a dependency for another package
```

**Comment by michael-manley** [comment]
This isn't a PCem bug more like a CMake/Arch bug

I see they call the wx-config app wx-config-gtk3, CMake won't see that.

A workaround is symlink /usr/bin/wx-config-gtk3 to /usr/bin/wx-config

**Comment by FredBezies** [comment]
Thanks for the feedback. Looks like I'll have to open a bug on Archlinux bugtracker.

**Comment by michael-manley** [comment]
@FredBezies Ok looking into the code, its actually an environment varable, so its

export WX_CONFIG=wx-config-gtk3

![image](https://user-images.githubusercontent.com/291225/163723591-7759ffa1-213a-4be2-9d49-365fcaa9c152.png)

**Comment by FredBezies** [comment]
> @FredBezies Ok looking into the code, its actually an environment varable, so its
> 
> export WX_CONFIG=wx-config-gtk3
> 
It fixes the building bug, but I have a coredump while using it. Bug report coming soon.
