### ISSUE TITLE
[git commit c7c8f5e] Pcem core dump on start, while trying to add a new PC.

### ISSUE THREAD

**Issue by FredBezies** [sarah-walker-pcem/pcem#135]
**Describe the bug**
While using pcem git [c7c8f5e](https://github.com/sarah-walker-pcem/pcem/commit/c7c8f5ee2f136a919790588de6b8b90cf6fab220), every single time I try to add a new PC, pcem coredumps.

**To Reproduce**

1. Get a build based on commit [c7c8f5e](https://github.com/sarah-walker-pcem/pcem/commit/c7c8f5ee2f136a919790588de6b8b90cf6fab220)
2. Launch pcem
3. Click on new button
4. Add a name 
5. Confirm you want a new emulated PC

**Expected behavior**
Going on and being able to add a new pc

**Host machine**

- OS: Archlinux
- git commit c7c8f5e
- cmake options: ```cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Debug -DPCEM_DEBUG_EXTRA=ON -DCMAKE_INSTALL_PREFIX=/usr -DUSE_NETWORKING=ON -DUSE_PCAP_NETWORKING=ON -DUSE_ALSA=ON -DPLUGIN_ENGINE=ON ..```

**Comment by FredBezies** [comment]
Adding a first backtrace.
[bt01.txt](https://github.com/sarah-walker-pcem/pcem/files/8502068/bt01.txt)

**Comment by FredBezies** [comment]
Build wxgtk with debug symbol, build once again pcem. Providing a more complete backtrace.
[bt02.txt](https://github.com/sarah-walker-pcem/pcem/files/8502133/bt02.txt)

**Comment by michael-manley** [comment]
There is some API changes going on and some builds from latest commit will be broken,

I am working on it. Linux builds seem to be the only ones affected atm

**Comment by michael-manley** [comment]
@FredBezies Try now, I think I found the problem, looks like the CD-ROM part was not checking correctly causing a segfault there

**Comment by FredBezies** [comment]
> @FredBezies Try now, I think I found the problem, looks like the CD-ROM part was not checking correctly causing a segfault there

Good catch. Thanks! 

Pcem is now launching the configuration panel without problem. Let's close this bug.
