### ISSUE TITLE
Plop Boot Manager crashes PCem

### ISSUE THREAD

**Issue by BEENNath58** [sarah-walker-pcem/pcem#137]
I am trying to prepare a Windows XP machine in PCem, and since Windows XP RTM requires booting from a CD, I am using a Plop Boot Manager Floppy to boot the machine and boot the CD from there, and it crashes while trying to boot from the CD.

**To reproduce**

Steps to reproduce the behaviour:
1. Set PCem to boot from the Plop Floppy and also insert the Windows XP ISO.
2. When it boots up, go to the CDROM option and press enter.

PCem crashes at this stage.

**Expected behaviour**

PCem was supposed to load the Windows XP setup at this stage following by the installation process which doesn't occur.

**Screenshots**

There is not much useful screenshot, but the following is the step where PCem crashes:
![pcemfail](https://user-images.githubusercontent.com/64649734/164972438-3cf9034d-70e1-40d4-9966-5a465ebd68c4.png)

**Emulator configuration**

- Machine: [Super 7] FIC VA-503+
- CPU: Pentium MMX 233
- Graphics card: 3Dfx Voodoo3 3000
- To be installed OS: Windows XP RTM
- Sound card: Sound Blaster AWE32
- RAM: 64MB
- HDD: IDE, 8192MB

**Host machine**

- OS: Windows 11
- Emulator version: PCem v17
- CPU: Ryzen  5 1600 AE

**Additional context**

PCem develops a log after crash, which says: "Device failed to request command"

**Comment by ruben-balea** [comment]
The **FIC VA-503+** BIOS can boot directly from CD **if you are using the standard IDE controller**, it does not work if you're using any SCSI controller, in such case you'll need a SCSI controller that allows booting from CD-ROM, I'm not sure if any of the emulated SCSI cards has that feature.
In case you do not remember how the BIOS SETUP worked a couple of decades ago I leave you a step-by-step guide with screenshots:

1 - Press **DEL** on the initial boot screen with the Energy Star logo to enter BIOS SETUP:
![Screenshot from 2022-04-24 20-31-13](https://user-images.githubusercontent.com/98262033/164991865-8d5c7d3b-9586-4e68-9f08-4fbc66d25bac.png)

2 - Using **UP**, **DOWN**, **LEFT**and **RIGHT** arrow keys move to the option you want to modify, in this case **BIOS FEATURES SETUP** and then press **ENTER** to access that setup page:
![Screenshot from 2022-04-24 20-24-31](https://user-images.githubusercontent.com/98262033/164991890-0a486a62-02d1-4afd-a806-c795b5db67ae.png)

3 - Use the arrow keys to move to **Boot Sequence** and then use **+**, **-**, **Page Up** and **Page Down** until you find the proper boot sequence **CDROM, C, A** and then press **ESC** to return to the main menu page:
![Screenshot from 2022-04-24 20-24-38](https://user-images.githubusercontent.com/98262033/164991894-7db1f96c-32df-4d4a-986f-c6dbc3a5b8ec.png)

4 - Use the arrow keys to move to **SAVE & EXIT SETUP** and press **ENTER** (You can also press **F10** as a shortcut for **SAVE & EXIT SETUP**)
![Screenshot from 2022-04-24 20-53-24](https://user-images.githubusercontent.com/98262033/164991927-73ce4c01-d3d9-494d-8506-210f30f5b3bc.png)

5 - Press **Y**:
![Screenshot from 2022-04-24 20-43-19](https://user-images.githubusercontent.com/98262033/164991932-1be7001d-faba-46af-a55a-b4bdcfb2386a.png)

6 - And then **ENTER** to confirm:
![Screenshot from 2022-04-24 20-44-31](https://user-images.githubusercontent.com/98262033/164991934-087925ae-168c-4f0b-9053-e3286c761a10.png)

7 - The machine will reboot and if there is a bootable CD mounted will boot from it:
![Screenshot from 2022-04-24 20-48-51](https://user-images.githubusercontent.com/98262033/164991936-cb47c960-9f99-46b9-b653-44d8f2516e84.png)

8 - That's it, you can proceed to install Windows XP as in a modern computer, enjoy!
![Screenshot from 2022-04-24 20-48-52](https://user-images.githubusercontent.com/98262033/164991937-5debe014-2abc-4bf7-bd3e-36e7a8102c58.png)

**Comment by ruben-balea** [comment]
Note: I used a machine with a 120 MHz Pentium to take the screenshots but I think you need to use at least a 233 MHz Pentium to be able to install Windows XP, I do not remember which versions of Windows do it, but I know that some check the CPU in the middle of the installation process and if it does not meet the minimum requirements, they abort the installation and you have to start over from scratch.

**Comment by BEENNath58** [comment]
Thanks, that fixed my problem. Probably Plop Boot Manager has an issue here, but I don't need it now anyways so all is well :)

**Comment by ruben-balea** [comment]
👍
