### ISSUE TITLE
[Feature] Is it possible to add hardware virtualization option to CPU emulation?

### ISSUE THREAD

**Issue by gennyo** [sarah-walker-pcem/pcem#140]
As a super Turbo button.

PCem has much better peripheral device emulation than Virtual Box and VMWare, make it a better choice for runing really old or exotic softwares, but CPU usage is high for low end machines like many old laptops I'm using. (i7-6600U can't run Windows 98 or 2k in constant speed)

**Comment by michael-manley** [comment]
The point of PCem is an emulator, not a virtualizer. If you do want things like this, QEMU does allow older device emulation and can run on KVM, or even on top of Hyper-V if you are running Windows.

Coding for this would be a major pain as you have 2 competing standards (Intel VT and AMD-V) and it would just not be worth it for what the project is.

**Comment by wilkovanderveen** [comment]
Intel VT and AMD-V do have the same abstractions so you only need to write the code once. So the competing standards are not an issue if you use the abstractions available.
