### ISSUE TITLE
Best Recommendations for PCem v18

### ISSUE THREAD

**Issue by JimboMumbo** [sarah-walker-pcem/pcem#146]
I've been using PCem v17 for a long time, and I always thought: "What if there would be great time to add Sound Blaster Live, Aureal Vortex, ATI Rage 128 Pro, and NVidia GeForce series, It's going to be much better! As for whoever is in charge of PCem, If you don't like my idea, that's okay, I should suggest something pacific next time. Good luck.

**Comment by leilei-** [comment]
See these threads for an idea of how difficult they'd be to emulate:

https://pcem-emulator.co.uk/phpBB3/viewtopic.php?t=3499

https://pcem-emulator.co.uk/phpBB3/viewtopic.php?t=3604

**Comment by JimboMumbo** [comment]
I see, thanks.

**Comment by michael-manley** [comment]
Maybe in the far future, but right now it's not practical. Closing for now.

**Comment by JimboMumbo** [comment]
Far future you say? Next year, buddy.
