### ISSUE TITLE
Compilation Help

### ISSUE THREAD

**Issue by AM7999** [sarah-walker-pcem/pcem#149]
When trying to compile pcem i get the following cmake error 
![image](https://user-images.githubusercontent.com/62681612/170845944-a12af1d1-9818-463c-afd3-d14c65cbd635.png)

Any help would be nice

**Comment by michael-manley** [comment]
You are missing a ton of information to even remotely get help. Should have least used the template.

I need to at LEAST know what OS this is on. But from what it seems, you are missing wxWidgets.

**Comment by AM7999** [comment]
I Am using Arch Linux ARM on a Nintendo Switch

**Comment by AM7999** [comment]
Alright then

**Comment by AM7999** [comment]
i know that this issue is already decently old now but it seems as if the package `wxgtk3` (though it may not contain the libs) is already pre-installed on my machine

**Comment by AM7999** [comment]
After fully installing wxWidgets and starting to compile pcem i get the following error 

`[1/321] Generating wx-ui/wx-resources.cpp
FAILED: src/wx-ui/wx-resources.cpp /home/alarm/pcem/src/wx-ui/wx-resources.cpp 
cd /home/alarm/pcem/src && wxrc -c /home/alarm/pcem/src/wx-ui/pc.xrc -o /home/alarm/pcem/src/wx-ui/wx-resources.cpp
wxrc: error while loading shared libraries: libwx_baseu_xml-3.1.so.6: cannot open shared object file: No such file or directory
ninja: build stopped: subcommand failed.
`

**Comment by michael-manley** [comment]
If you want any more help on this, please take it to the forum @ https://pcem-emulator.co.uk/phpBB3/viewforum.php?f=3

GitHub is for bug reports, and development tasks, not how to build PCem questions.
