### ISSUE TITLE
Problem with the latest pcem dev build

### ISSUE THREAD

**Issue by AITUS95** [sarah-walker-pcem/pcem#156]
Hi, when I try to create a machine with the latest dev build, the hdd is not recognized and the ram always remains unchanged, I also tried to manually modify the machine configuration file but the values are reset once pcem is opened .

Operating system: Windows 10
Build: PCem-vNext-Windows-MINGW64-140 (also 32-bit)

**Comment by bobba84** [comment]
I had the same issue - also all Pentium boards reset to Pentium 75MHz CPU every time they are opened / reconfigured.

Win11 and commit 6f69f3e #140

**Comment by unreal9010** [comment]
The issue has since been fixed. However, since last two commits, there are some performance issues. At the moment I can hardly go above Pentium II 300 on my 12900 KF whereas before I could do Pentium II 350 without issues.

**Comment by AITUS95** [comment]
the problem is fixed, I think the regressions will be fixed with the final switch to QT.
