### ISSUE TITLE
-O3 and -O2 optimization cause machines with the dynamic recompiler enabled to hang permanently (Linux)

### ISSUE THREAD

**Issue by pghvlaans** [sarah-walker-pcem/pcem#157]
**Describe the bug**
On the most recent commit (`6f69f3e`), opening a machine with the dynamic recompiler enabled results in an apparently permanent hang if `-O3` (default) or `-O2` optimization was used to build `pcem`. `-O1` optimization works as expected.

`-O3` optimization with
```
static inline void __attribute__((optimize="O1"))) exec_recompiler(void)
```
at `src/cpu/386_dynarec.c:263` also works as expected.

**To Reproduce**

1. Build `pcem` on Linux with `-O2` or `-O3` optimization
2. Open a machine with the dynamic recompiler enabled

**Expected behavior**
For the machine to open without hanging.

**Emulator configuration**
A machine with the dynamic recompiler enabled. I tried two:

- Machine: Intel VS440FX
- CPU: Pentium Pro 180
- Graphics/sound cards: Cirrus Logic CL-GD5434 / Sound Blaster 16 

- Machine: Itautec Infoway Multimidia
- CPU: Pentium 133
- Graphics/sound cards: 3DFX Voodoo 3 2000 / Sound Blaster AWE32

**Host machine**
- OS: Slackware64 15.0
- Emulator version: dev (`6f69f3e`)
- GCC: 11.2.0
- wxWidgets: 3.0.5

**Additional context**
Even at `-O1`, the dynamic recompiler appears to be performing better than it does at `-O0`.

This may or may not be helpful, but using `-fPIC` with any level of optimization at `386_dynarec.c:263` results in an instant crash rather than a hang.

**Comment by michael-manley** [comment]
This is exactly an Issue I been noting, and it seems to be on OS's with a newer version of GCC.

I use Debian, so I'm on 
gcc version 10.2.1 20210110 (Debian 10.2.1-6) 

Maybe GCC 11 is being overzealous on some optimizations?

**Comment by pghvlaans** [comment]
That's interesting. The default GNU extensions for C and C++ actually changed between the two versions. I tried setting `std` and `std++` to the 10.2 defaults, but no luck.

No more time at the moment, but I'll take another look at the optimizer flags added by -O2 later and see if anything looks promising. Please let me know if there's anything you'd like to check on GCC 11.2.

**Comment by pghvlaans** [comment]
It looks like GCC 11 at -O2 and up might have been inlining the `exec_recompiler` function poorly. Using -O3,
```
static void __attribute__((noinline)) exec_recompiler(void)
```
results in the program running as expected. Performance appears to be just about the same as optimizing `exec_recompiler` at -O1.

Unfortunately, I don't have any OS with GCC 10.2 on bare metal at the moment, so I can't really test whether `noinline` causes a performance hit relative to -O3 for `exec_recompiler`. I'll make a PR just in case, but I'm happy to patch my own builds if the change causes trouble for GCC 10.x.
