### ISSUE TITLE
V18 Switch to Qt

### ISSUE THREAD

**Issue by michael-manley** [sarah-walker-pcem/pcem#158]
V18 other than bug fixes will also make a switch to Qt, as WxWidgets is causing me to pull my hair out. This will also mean that the SDL separation code will happen in V18 also.

I will also change API code to use the QT Plugin engine.

The first steps will be separating SDL Code from WxWidgets, and putting WxWidgets as a deprecated GUI.

Add a -DPCEM_GUI_MODE with the following options, SDL, WxWidgets, Qt
SDL will be raw SDL, with no GUI mode, this is the first model to be implemented and will only work with a config file specified on the command line
WxWidgets will be the current GUI.
Qt will be the new GUI

I was pushing off not doing this as Qt can be bloated, but since I really am just going to use QT Core and nothing else, should be fine.

Comments welcome. This will also allow the Android planned port to be sooner, possibly V19

**Comment by unreal9010** [comment]
Great! I see my proposal from April wasn't a bad idea. Indeed, many of the current regressions are WxWidgets-related.
Might help to reduce some of these.

**Comment by michael-manley** [comment]
I have noticed wxWidgets supports a Qt backend. I think for now I will use that backend to prep a slow migration over to Qt.
