### ISSUE TITLE
Flathub build

### ISSUE THREAD

**Issue by AsciiWolf** [sarah-walker-pcem/pcem#164]
I am working on a PCem Flatpak and want to publish it on [Flathub](https://flathub.org). Please, let me know whether you are interested in co-maintaining the Flatpak. Thanks! :-)

**Comment by AsciiWolf** [comment]
I have decided to base my Flatpak on the 86Box fork instead. I am closing this issue.

Here is an archive with the original files from my PCem Flatpak in case someone wants to take over the work:
[uk.co.pcem_emulator.pcem.zip](https://github.com/sarah-walker-pcem/pcem/files/9143715/uk.co.pcem_emulator.pcem.zip)

**Comment by BlastBlaster17** [comment]
I think this should be re-opened. I would love to see a Flatpak for PCem.

**Comment by AsciiWolf** [comment]
Feel free to create a new ticket for this. I am not going to work on the PCem Flatpak so this ticket and its description would be misleading.
