### ISSUE TITLE
Mental Math Games glitch on new PCEM

### ISSUE THREAD

**Issue by KoghaandSooga** [sarah-walker-pcem/pcem#165]
I got hacked by MS update and Dad had to go thru hell trying to get my computer to even turn on again.  Luckily most of my files were backed to my elements but not PCEM sadly.  I had to redo it and now having this same problem.  I guess the bios doesn't matter.

Unfortuantely I lost my previous PCEM so had to redownload it. Used the same settings as the other thread yet am having the issue again  though this time it doesn't seem to matter which one I choose. I now have to have all sound off to control the mouse in the game or it freezes after the lights countdown and the door opens up:

  If I choose one or the other then I can control the mouse and type the math problems in to change his direction(s) to eat up the cheese and avoid mouse traps. can control the mouse and type the math problems in to change his direction(s) to eat up the cheese and avoid mouse traps.

Note: This time I did use AWE32 just by habit. Maybe that's the problem all along? I'll try it without and try with Voodoo 3 installed to see if that may be the issue. Perhaps the tiny mouse animation requires Voodoo?  It seems a game that old shouldn't though.

**Comment by KoghaandSooga** [comment]
Voodoo 3 was an epic fail. Locked my PCEM and then never installed it.   I'm back to square one.  PCEM seems not to be compatible with this one game.  Weird.

**Comment by unreal9010** [comment]
You've just opened a separate thread on the same issue like you did about few weeks ago and which turned out to be UNRELATED (see [here](https://github.com/sarah-walker-pcem/pcem/issues/163)) to PCem. Please close both issues and stop spamming.

**Comment by KoghaandSooga** [comment]
I'm going to shut this topic down in 5.4.3 2 1. CLAAAAALOOOOOOSED!
