### ISSUE TITLE
[BUG] RTC Sync

### ISSUE THREAD

**Issue by rchipp42** [sarah-walker-pcem/pcem#17]
**Describe the bug**
When you create a VM (any BIOS) with the RTC sync option enabled, then start it and enter the ROM SETUP utility, the time/date is reported as the BIOS default. However, when you stop the machine, disable RTC sync, start the machine, stop the machine, re-enable RTC sync, start the machine and enter the ROM SETUP utility, the reported date/time is the host system date/time.

**Reproduction Steps**
1. Create a new machine (any BIOS) with the RTC sync option enabled.
2. Start the machine and enter ROM SETUP
3. The date/time reported is the BIOS default value, not the host value.

**Expected behavior**
The expected behavior is that the guest time is synced with the host time

**Workaround Steps**
1. Stop the machine.
2. Disable RTC sync
3. Start the machine
4. Stop the machine
5. Re-enable RTC sync
6. Start the machine
7. Enter the ROM SETUP utility
8. The reported date/time is the host system date/time

**Emulator configuration**
 - Machine: N/A Bug occurs on every one I've tried.
 - CPU: N/A Bug occurs on every one I've tried.
 - Graphics/sound cards: N/A Bug occurs on every one I've tried.
 - Installed OS: N/A Bug occurs on every one I've tried.

**Host machine**
 - OS: Kubuntu 21.04
 - Emulator version: v17
 - Any other relevant information: Built from source using release and networking configure flags

**Comment by sarah-walker-pcem** [comment]
Fixed in commit 5f772fdf.
