### ISSUE TITLE
Maniac Mansion 2: Day of the tentacle sound effects are jumbled up and the synthesized music plays wrong.

### ISSUE THREAD

**Issue by sudodebian** [sarah-walker-pcem/pcem#171]
Hello, while playing Day of the Tentacle, when i removed my headphones to do something, the sounds get jumbled up and the music plays wrong when playing with Bernard.

How to reproduce this:
While the music is playing, remove the headphones.

System:
Manjaro Ruah 21.3.7 (XFCE version)
AMD R5 Graphics APU with A8-7410
RAM: 4,00 GB (only 3,37 GB usable)

Thanks.

**Comment by unreal9010** [comment]
Please provide details on the configuration of your emulated machine (CPU, OS, video card, sound card). 
Note that DOTT has some serious issues with AudioPCI-based cards.

**Comment by sudodebian** [comment]
Ok so i discovered that it was a problem with my version of DOTT for some reason. Closing this thread.
