### ISSUE TITLE
How to build pcem v18 beta?

### ISSUE THREAD

**Issue by XDOneDude** [sarah-walker-pcem/pcem#175]
i know that in the beta or alpha or pcem v18 added matrox millennium and some new machines and i want to look for how to build in windows cmake? i tried everything i tried to use linux but, same error about openal

**Comment by XDOneDude** [comment]
and i have install openal library

**Comment by Derailedzack** [comment]
Do you have the development package installed for openal?

**Comment by XDOneDude** [comment]
yes

**Comment by XDOneDude** [comment]
i have actually installed

**Comment by XDOneDude** [comment]
the openal dll and the sdk

**Comment by XDOneDude** [comment]
in windows but still work on linux like sdl2 that i already resolved

**Comment by Derailedzack** [comment]
Do you have the development packages installed for all the dependencies of PCem?

**Comment by XDOneDude** [comment]
i installed all except wxWidgets 3.x

**Comment by XDOneDude** [comment]
i still dont know how to link openal to cmake
and sdl2 i know

**Comment by XDOneDude** [comment]
well i compiled but when i compile in cmake it appears only these files in build folder
![cmakedd](https://user-images.githubusercontent.com/106700244/188033920-66922304-0ca6-4934-9a40-7a89ab8be4f9.png)

**Comment by XDOneDude** [comment]
in linux :\

**Comment by Derailedzack** [comment]
What errors do cmake give you?

**Comment by XDOneDude** [comment]
in src very much

**Comment by XDOneDude** [comment]
![baderror](https://user-images.githubusercontent.com/106700244/188170407-7c6b7b3a-8279-46de-ae81-69d15452a51c.png)

**Comment by XDOneDude** [comment]
i needed to fix so much things

**Comment by XDOneDude** [comment]
i fixed it with make but only have builded the target
