### ISSUE TITLE
how to get the pcem v18 beta roms

### ISSUE THREAD

**Issue by XDOneDude** [sarah-walker-pcem/pcem#176]
well, i downloaded a build of pcem v18 beta from actions but i still need the pcem v18 beta roms to test matrox millennium

**Comment by eddmanx** [comment]
Github is not a support page. Read the general rules sticky thread on the forum regarding roms.

**Comment by michael-manley** [comment]
Not only that, we don't provide ROMs, nor will we tell you how to get them, you will have to figure that out on your own, Google is your friend.
