### ISSUE TITLE
AMD 5x86 CPUID

### ISSUE THREAD

**Issue by caiot5** [sarah-walker-pcem/pcem#18]
**Describe the bug**
All BIOS ROMs available report wrong CPUID for Am5x86 P75 and P75+.
It is being recognized as Am486DX4-S at 120MHz (for Am5x86 P75 133MHz) and 150MHz respectively.
I know it is not right because I have a SiS 496/497 based board myself with a Am5x86 P75 and it does recognize the CPUID/CPUTYPE correctly and also the clock speed.

**To Reproduce**
Create a new machine with the hardware specified above and start it. ;)

**Expected behavior**
CPUID/Type should match CPU selected.

**Screenshots**
<img width="645" alt="image" src="https://user-images.githubusercontent.com/9531222/119296817-0e578180-bc30-11eb-8c9c-85b4c4dd98f8.png">
<img width="543" alt="image" src="https://user-images.githubusercontent.com/9531222/119296908-465ec480-bc30-11eb-8a49-cbf811068b88.png">

**Emulator configuration**
 - Machine: [486] Award SiS 496/497
 - CPU: AMD Am5x86 P75
 - Graphics/sound cards: Trident TGUI9440 / SoundBlaster 16
 - Installed OS: Windows 95 OSR2.5

**Host machine**
 - OS: macOS Mojave 10.14.6
 - Emulator version: v17 (but seems to affect since v14, which was the first one that I used)

**Additional context**
None

**Comment by sarah-walker-pcem** [comment]
Not a bug - the BIOS used with this configuration (09/07/95) predates the Am5x86 so can not identify it. Switching to a newer BIOS (I tried 10/02/95) will correctly identify the CPU as an AMD-X5-S.
