### ISSUE TITLE
how to send files to the os in pcem 

### ISSUE THREAD

**Issue by dananothername** [sarah-walker-pcem/pcem#180]
i mean i installed an os inside pcem and i want to know how to send files to it 
if possible in libTAS too

**Comment by JosepMaJAZ** [comment]
Better use the boards for questions:

https://pcem-emulator.co.uk/phpBB3/viewforum.php?f=2

I was looking for a post about this, but I couldn't find the one I was looking.
You have several options, an easy one is to have an application that generates .iso files and then mount the .iso on PCem.
Other options are to have some sort of http server to serve files. [hfs](https://www.rejetto.com/hfs/ ) is one tiny application for that for windows.

**Comment by michael-manley** [comment]
Yes, please post questions on the forums, as there more users there that can help. This area is more development oriented, and I tend to close tickets that are not bug or feature requests.

**Comment by dananothername** [comment]
then i change my bug report to feature request 
let pcem run os after 2000s
