### ISSUE TITLE
Socket 7 Windows 2000 doesn't install. Freezes on bootup

### ISSUE THREAD

**Issue by KoghaandSooga** [sarah-walker-pcem/pcem#181]
On Socket 7 I did the setup of this post here minus the network card:
:https://pcem-emulator.co.uk/phpBB3/viewtopic.php?t=3763
[Re: Windows 2000 in PCem](https://pcem-emulator.co.uk/phpBB3/viewtopic.php?

Working very well for me, sound is clear and absolutely no LAG.
My config for win 2000 in PCEM:
resolution 1024 x 768 16 bit
MB [Super7] FIC VA-503+
Mobile Pentium MMX 300
RAM 512 MB
S3 Virge/DX Fast VLB/PCI
No Voodoo Graphics
SB 16
Novell NE 2000 0x300-31F IRQ 10

And the result is I can get to where it asks me to remove any floppies which I boot from the CD and then it hangs at Atapi CD Rom when rebooting. It never gets past it.  

**To Reproduce**

**Expected behavior**
Windows 2000 to finish installing which it does on Pentium II but it's too laggy to be of any use on my I7. 

**Screenshots**

**Emulator configuration**

- Machine: [e.g. IBM AT, AMI 486 clone etc]
- CPU:
- Graphics/sound cards:
- Installed OS

**Host machine**

Windows 10 Home  I7 8th gen.

**Additional context**

**Comment by KoghaandSooga** [comment]
Okay: Out of desperation I found this tutorial and I think I fixed the problem at least temporarily.  https://youtu.be/mfipTBFDhiw?t=571 He does a thing where you press C at this point in the video. I just pressed enter which obviously resulted in the thing hanging when rebotting after formatting.  

Do you know why pressing C seemed to fixed it? I couldn't ever get it to go past https://youtu.be/mfipTBFDhiw?t=831 this point as it would hang at Atapi CD Rom for ever only on Socket 7.  Gigabyte Pentium II doesn't have this problem where I had to press C.

**Comment by unreal9010** [comment]
You need to use the forums for such things, not GitHub since it's purpose is to report and diagnose PCem bugs. This is not a PCem bug (it works perfectly on my end, meaning there has to be something wrong with your setup) so please close this issue.
