### ISSUE TITLE
This Kernel Requires an x86-64 CPU but only detected i686 CPU 

### ISSUE THREAD

**Issue by dananothername** [sarah-walker-pcem/pcem#184]
this happens when i try to imstall 32 bit os like android os or fire os
+ another question how can i connect it to internet , my emulated win xp doesn't like offline installer

**Comment by unreal9010** [comment]
PCem's emulated hardware is not suitable for running Android or Fire OS.
Windows XP should install without problems in offline mode. Bear in mind, though, that the emulated hardware is not particularly great for running XP.

**Comment by dananothername** [comment]
i am a TASer so pcem is my only chance
what i want is to know how to add network hardware in pcem
for online installer, like java runtime won't install offline

**Comment by leilei-** [comment]
PCem doesn't emulate smartphones.
