### ISSUE TITLE
Cannot exit the emulation normally on macOS

### ISSUE THREAD

**Issue by TomoshibiAkira** [sarah-walker-pcem/pcem#185]
**Describe the bug**
The emulation window will hang upon closing instead of exiting back to the config selector normally.

**To Reproduce**

1. Create any config and run the emulation.
2. Close the emulation window.
3. The window will hang for a few seconds and then exit back to the config selection UI.

**Expected behavior**
The emulation window should close normally.

**Host machine**

- OS: macOS Monterey 12.6
- Apple Silicon M2
- Using the current ``dev`` branch.
- using ``cmake -G "Xcode"`` and ``xcodebuild`` to compile.

**Additional context**
I did some initial digging and found out the problem is related to ``renderer_stop()`` (L691) in ``wx-sdl2-display.c``.
Since on macOS, PCem won't use threads for rendering, it should never use ``renderCond`` to wait for the thread to quit.
The line in question has a ``!`` before the preprocessor ``PCEM_RENDER_TIMER_LOOP``. Might be a typo.
Fixing this ifdef block can fix this bug.

There are some other issues w.r.t. the cmake files while compiling for an Apple Silicon machine, I'll open a pull request for these.

**Comment by barttenbrinke** [comment]
@TomoshibiAkira what architecture are you compiling? I get a
```Undefined symbols for architecture arm64:
  "_codegen_backend_epilogue", referenced from:
  ...
  ld: symbol(s) not found for architecture arm64
  ``` 
  when I try to repeat your build.
