### ISSUE TITLE
error 5

### ISSUE THREAD

**Issue by FranzGsmer** [sarah-walker-pcem/pcem#188]
hey can you help im having an error here is the entire thing: 08:25:14 Error Directory 'D:\shaderpacks\PCemV17Win\screenshots/"
couldn't be created (error 5: access is denied.)

**Comment by ruben-balea** [comment]
Have you tried creating it manually? maybe you need admin permissions or something...

**Comment by michael-manley** [comment]
Looks to be permissions to me, check that directories permissions or run PCem as Administrator. This isnt a bug with PCem itself.
