### ISSUE TITLE
README.md has a little typo

### ISSUE THREAD

**Issue by vaparetia** [sarah-walker-pcem/pcem#189]
Hello, 
I downloaded v17 from your site at [https://pcem-emulator.co.uk/downloads.html] and noticed a typo on README.md line 22.

I believe the "./configure --enable-release" needs to be "./configure --enable-release-build" according to the text on lines 33 - 40. Plus it doesn't seem to be matching what is on github, so maybe just a left over when people switched positions?

Not a big deal. Just letting you know. :)

**Comment by michael-manley** [comment]
Thanks, but being v18 and beyond don't use Autotools anymore, this is a moot point. But appreciate the alert :)
