### ISSUE TITLE
Voodoo Banshee/3 packed chain4 stuff missing and scrambled display

### ISSUE THREAD

**Issue by TC1995** [sarah-walker-pcem/pcem#22]
**Describe the bug**
Looks like packed chain4 stuff is not implemented in the Banshee/3, as a result, drivers for Windows 9x/NT/2000 would result in scrambled display, rendering issues like doubled desktop and stretched and so on.

**To Reproduce**
Pretty simple, just set 8bpp and up (16bpp/24/32bpp) in the operating systems mentioned above once drivers are installed. 

**Expected behavior**
The way it displayed fine before the packed chain4 stuff was implemented.

**Screenshots**

**Emulator configuration**
 - Machine: Any PCI-based machine
 - CPU: Intel/AMD socket 7/etc
 - Graphics: Voodoo 3/Banshee.
 - Windows NT/9x/2000/XP

**Host machine**
 - OS: Windows 10.
 - Latest PCem v17 commit with the packed_chain4 stuff in.

**Additional context**

**Comment by sarah-walker-pcem** [comment]
Should be fixed in commit e069ec73.
