### ISSUE TITLE
How to download beta?

### ISSUE THREAD

**Issue by Flo9696** [sarah-walker-pcem/pcem#226]
How do I download the beta version, all links are expired!

**Comment by mikew** [comment]
Since this repo uses GitHub Actions, technically all you have to do is fork it and trigger a build. This repo even has a nice Release build trigger.

I've gone ahead and done that: https://github.com/mikew/pcem/actions/runs/5527387920#artifacts

**Comment by rilysh** [comment]
PCem already has a GH actions setup, just head over to actions tab and download the newest build. Example [link](https://github.com/sarah-walker-pcem/pcem/actions/runs/5528873642).

**Comment by mikew** [comment]
The artifacts expire after 90 days, and when this issue was created there hadn't been any builds in about 115 days.

**Comment by michael-manley** [comment]
I am going to set somthing up to upload dev builds to my server so if they do expire there is a mirror of the latest.

**Comment by Flo9696** [comment]
> I am going to set somthing up to upload dev builds to my server so if they do expire there is a mirror of the latest.

That sounds good!
