### ISSUE TITLE
Windows XP installation freezes before OOBE

### ISSUE THREAD

**Issue by vadosnaprimer** [sarah-walker-pcem/pcem#230]
When installing Windows XP on PCem according to [this guide](https://tasvideos.org/EmulatorResources/PCem/Windows/Configurations) (and with various deviations from it) everything works fine until the point when you're asked about a resolution change:

![изображение](https://github.com/sarah-walker-pcem/pcem/assets/7092625/1f33d4b6-56b7-428d-b73e-64ae8bbc4019)

When you agree to it, it does change the resolution and then shows this screen:

![Screenshot](https://github.com/sarah-walker-pcem/pcem/assets/7092625/d026e4b6-66c5-4ba4-b2bf-b621b33f56c5)

Then it never gets past that screen even after many hours of waiting.

To be fair, if you reboot the machine, it's possible to use Windows XP just fine.

**Expected behavior**
The thing that is supposed to go after the `Please wait...` screen is Windows [out-of-box-exerience](https://www.youtube.com/watch?v=dFObbmMqwFM) sequence.

**Emulator configuration**
[xp.zip](https://github.com/sarah-walker-pcem/pcem/files/12329318/xp.zip)
I tried changing things around but it didn't help,

**PCem versions I used**
- v17 on Windows 7 (this one worked a few times and I got into OOBE)
- https://github.com/sarah-walker-pcem/pcem/commit/5df4a1f84f40e5fa892320f83b72d2810725b70b on xubuntu 22 (via vmware 15)

**XP versions I tried**
- 5a6b959ad24d15dc7ebd85e501b83d105d1b37c6  en_windows_xp_home_with_service_pack_3_x86_cd_x14-92413.iso
- 1c735b38931bf57fb14ebd9a9ba253ceb443d459  en_windows_xp_professional_with_service_pack_3_x86_cd_x14-80428.iso
- f43b5bad8db60a25bb696183153ef856af839573  en_windows_xp_home_n_with_service_pack_3_x86_cd_x14-92393.iso

**Additional info**
Debug build log of the freeze
[freeze.zip](https://github.com/sarah-walker-pcem/pcem/files/12329339/freeze.zip)

I also tried to read WinXP source code to figure out which step it dies at exactly, but never figured out the global sequence of events, only individual parts that are scattered around and are not very helpful without debugging.

**Comment by KoghaandSooga** [comment]
> When installing Windows XP on PCem according to [this guide](https://tasvideos.org/EmulatorResources/PCem/Windows/Configurations) (and with various deviations from it) everything works fine until the point when you're asked about a resolution change:
> 
> ![изображение](https://user-images.githubusercontent.com/7092625/260296115-1f33d4b6-56b7-428d-b73e-64ae8bbc4019.png)
> 
> When you agree to it, it does change the resolution and then shows this screen:
> 
> ![Screenshot](https://user-images.githubusercontent.com/7092625/260296156-d026e4b6-66c5-4ba4-b2bf-b621b33f56c5.png)
> 
> Then it never gets past that screen even after many hours of waiting.
> 
> To be fair, if you reboot the machine, it's possible to use Windows XP just fine.
> 
> **Expected behavior** The thing that is supposed to go after the `Please wait...` screen is Windows [out-of-box-exerience](https://www.youtube.com/watch?v=dFObbmMqwFM) sequence.
> 
> **Emulator configuration** [xp.zip](https://github.com/sarah-walker-pcem/pcem/files/12329318/xp.zip) I tried changing things around but it didn't help,
> 
> **PCem versions I used**
> 
> * v17 on Windows 7 (this one worked a few times and I got into OOBE)
> * [5df4a1f](https://github.com/sarah-walker-pcem/pcem/commit/5df4a1f84f40e5fa892320f83b72d2810725b70b) on xubuntu 22 (via vmware 15)
> 
> **XP versions I tried**
> 
> * 5a6b959ad24d15dc7ebd85e501b83d105d1b37c6  en_windows_xp_home_with_service_pack_3_x86_cd_x14-92413.iso
> * 1c735b38931bf57fb14ebd9a9ba253ceb443d459  en_windows_xp_professional_with_service_pack_3_x86_cd_x14-80428.iso
> * f43b5bad8db60a25bb696183153ef856af839573  en_windows_xp_home_n_with_service_pack_3_x86_cd_x14-92393.iso
> 
> **Additional info** Debug build log of the freeze [freeze.zip](https://github.com/sarah-walker-pcem/pcem/files/12329339/freeze.zip)
> 
> I also tried to read WinXP source code to figure out which step it dies at exactly, but never figured out the global sequence of events, only individual parts that are scattered around and are not very helpful without debugging.

Man I'd LOVE for this project to keep going to the XP era just for reference sakes: even if we can't exactly emulate the bios yet it doesn't mean research shouldn't quit because then we can have full coverage of hardware specs. Which then it will be a literal time machine of PC's/Laptops if they ever do Laptop models.   Imagine someday emulating a Dell Latitude D600 to relive your childhood laptop or something once home CPU's get there.

**Comment by EnginnerDog** [comment]
This is normal, you need to hard-reboot

**Comment by vadosnaprimer** [comment]
> This is normal, you need to hard-reboot

Can you give more info on the conditions it's normal in?

**Comment by EnginnerDog** [comment]
OOBE not loading is common on VMs and maybe this is because that the OOBE
refuses to load

**Comment by ruben-balea** [comment]
It also does the same thing on (some?) physical computers, it can get stuck on that screen for hours

**Comment by EnginnerDog** [comment]
Best thing you could do back in the day was restart the computer. Always worked for me.
