### ISSUE TITLE
Support MISTer BIOS

### ISSUE THREAD

**Issue by DMJC** [sarah-walker-pcem/pcem#233]
Can someone add support for the MISTer AO486 bios? This is an open source BIOS for booting a 486 system.
https://github.com/MiSTer-devel/ao486_MiSTer/blob/master/releases/boot0.rom
https://github.com/MiSTer-devel/ao486_MiSTer/blob/master/releases/boot1.rom

**Comment by ruben-balea** [comment]
That BIOS can't boot any real 486 system and for PCem you need a BIOS that works on real hardware.
MISTer is hardware but it's closer to a hardware implementation of Bochs or DOSBox than to a real PC or PCem, it's very simplified and only needs a BIOS for compatibility "to talk" with the OS, all emulated devices are preconfigured and ready to work while in PCem the BIOS needs to configure and initialize the hardware at boot time like on a real computer.

If you need a very customized emulation with DOSBox-X you can configure (almost?) everything easily using a GUI, so I think it would be a better option than trying to emulate another emulated system in PCem.
