### ISSUE TITLE
Simple update on README.md

### ISSUE THREAD

**Issue by Soufleuse** [sarah-walker-pcem/pcem#239]
Hi,

my issue is a simple one on README.md. I did not see PCAP as a required dependency. I needed that library to run cmake command. I'm on KUbuntu 22.04.

If PCAP is there,please close immediately that issue.

**Comment by michael-manley** [comment]
It is needed by default, but you can build without it if you do -DUSE_PCAP_NETWORKING=OFF

Its requirement is listed under the options portion, same with MIDI Dependencies
