### ISSUE TITLE
PCem release builds crash when running Windows NT 3.1 when pausing/stopping MPU-401 MIDI playback

### ISSUE THREAD

**Issue by Cacodemon345** [sarah-walker-pcem/pcem#24]
**Describe the bug**
If an attempt is made to pause/stop MIDI playback in Windows NT 3.1's Media Player, PCem crashes.

**To Reproduce**
1. Boot up Windows NT 3.1.
2. Open File Manager.
3. Open any of the sample MIDI files included with the installation in the WINNT directory.
4. While the MIDI is playing in the Media Player, press the Pause/Stop button.
The emulator should now freeze and crash.

**Expected behavior**
The MIDI playback should pause/stop properly.

**Emulator configuration**
 - Machine: FIC VA-503+
 - CPU: Pentium OverDrive MMX 125
 - Graphics/sound cards: Tseng ET4000AX, Sound Blaster AWE32
 - Installed OS: Windows NT 3.1

**Host machine**
 - OS: Manjaro Linux.
 - Emulator version: Git version e069ec73386b3e4c8e6f1fe9d3e2463fa4650891

**Additional context**
Windows NT 3.1 is using the beta Sound Blaster 16 drivers. The emulator is also using virtualized ALSA rawmidi ports which is connected to FluidSynth.

**Comment by sarah-walker-pcem** [comment]
Anything in the log?

**Comment by Cacodemon345** [comment]
The logger is disabled when it is compiled as a release build, which is also where the crash will manifest. The crash doesn't happen on debug builds.

**Comment by sarah-walker-pcem** [comment]
Try enabling the log for all builds - in pc.c, comment out or delete lines 99 and 116 (#ifndef / #endif)

**Comment by Cacodemon345** [comment]
[pcem.log](https://github.com/sarah-walker-pcem/pcem/files/6618343/pcem.log)
This is the log I get before the crash.

**Comment by sarah-walker-pcem** [comment]
Fixed in commit e781f6b4.
