### ISSUE TITLE
Voodoo 2: Graphics glitches in Nightmare Creatures

### ISSUE THREAD

**Issue by unreal9010** [sarah-walker-pcem/pcem#25]
**Describe the bug**
When running Nightmare Creatures (full retail version) with Voodoo 2 it is likely to encounter graphics glitches while playing. 
I got greeted by some of them even at the start of the very first level (see screenshots for details). When I existed level for the Main Menu, shadows beneath main characters suddenly became red. 
 I tried the following Voodoo 2 drivers: Generic Voodoo 2 DX6 driver (dated October 1998), Generic Voodoo 2 DX6 driver (dated January 1999), Diamond Monster ll DX5 driver from Diamond's own Installation Disc (released in early 1998) - on another VM with DX 5 installed, Diamond Monster ll DX6 driver (dated October 1998).  Each time the same result.
Game works great and without any issues with Voodoo 3, though.   

**To Reproduce**
1. Start your virtual machine
2. Run Nightmare Creatures
3. Start the game

**Expected behavior**
Graphics without glitches.

**Screenshots**
![ncreatures2](https://user-images.githubusercontent.com/84349460/121081156-9d41cd80-c7dc-11eb-9249-c24a6b04bbd0.JPG)
![ncreatures](https://user-images.githubusercontent.com/84349460/121081159-9e72fa80-c7dc-11eb-98ec-9a301e35ebab.JPG)

**Emulator configuration**
 - Machine: GA-686BX
- CPU: Pentium ll 233
- Graphics/sound cards: Voodoo 2/SB 128
- OS: Windows 95

**Host machine**
 - OS: Windows 10
 - PCem v17
 - i7 6700, GTX 1060

**Additional context**

**Comment by sarah-walker-pcem** [comment]
Reproduces with driver V3.01.00 (11th Oct 1998), but not with driver V3.02.02 (27th Jan 2000). Will need to verify on real hardware.

**Comment by unreal9010** [comment]
No such issues with DX5 drivers dated 7/14/1998.
