### ISSUE TITLE
MSYS2 instructions outdated and not working.

### ISSUE THREAD

**Issue by nicklamn** [sarah-walker-pcem/pcem#276]
I have tried for a few hours now to compile on MSYS2. I have tried Mingw-w64, msys2 msys, all of them and only mingw works to generate Cmake files.
However, running ninja, as the next step shows, results in somewhat garbled text as output, then ninja exits. I have seen that others got it to work. This is happening with the MSYS2 07-27-2024 build, pacman -Syu has been ran.
I suppose this project no longer supports windows?
I see no cross-compilation instructions, and tried myself but failed with many file missing and not implemented errors with mingw-w64.
On windows 11 24h2 x86-64 on a macbook pro 2017 15".

**Comment by ruben-balea** [comment]
I just downloaded the repo using:

`git clone https://github.com/sarah-walker-pcem/pcem`

and then built it under MSYS2-MING64 without any error:

![image](https://github.com/user-attachments/assets/a0a475c9-ade7-4327-9cb2-8732ac60b501)

Then pcem.exe asks for a bunch of DLL files that you can copy from \mingw64\bin

**I did the same under MSYS2-MINGW32 and it worked too.** Of course for the 32-bit executable I used the 32-bid DLLs from \mingw32\bin

**Comment by ruben-balea** [comment]
Try launching MSYS MSYS2 and paste this to make sure you have everything you may need installed:

`pacman -Sy mingw-w64-{i686,x86_64}-ntldd-git mingw-w64-{i686,x86_64}-toolchain mingw-w64-{i686,x86_64}-SDL2 mingw-w64-{i686,x86_64}-openal mingw-w64-{i686,x86_64}-wxWidgets mingw-w64-{i686,x86_64}-libpcap mingw-w64-{i686,x86_64}-cmake mingw-w64-{i686,x86_64}-ninja mingw-w64-{i686,x86_64}-libpcap mingw-w64-{i686,x86_64}-ninja
`

**Comment by nicklamn** [comment]
Ok, one more go at this.
I opened MSYS2 Mingw64, ran the above command. As before, it complained about libpcap and wxwidgets not having i686 packages, so I removed the i686 part. I ran the cloned and followed the instructions and it worked. Thank you, I have no idea what went wrong last time.
