### ISSUE TITLE
Has this tool been abandoned by original author or has the website just been hacked?

### ISSUE THREAD

**Issue by IceKickr** [sarah-walker-pcem/pcem#31]
Unable to access the web site and wiki site says "this has been discontinued as of 6/12"

**Comment by laetemn** [comment]
ALL files...

http://pcem-emulator.co.uk/files/

**Comment by mirrornoir** [comment]
I explained a bit more here: https://github.com/sarah-walker-pcem/pcem/issues/32#issuecomment-860332368

**Comment by pcem-maintainer** [comment]
Duplicate of #32
