### ISSUE TITLE
Website down / hacked?!

### ISSUE THREAD

**Issue by darkguy2008** [sarah-walker-pcem/pcem#32]
Sorry to bother, but it seems that https://pcem-emulator.co.uk/ is down (it's throwing a blank site) and the forum (which was a good and useful source of information) says it's over and that it's not fun anymore? What in the world?

![image](https://user-images.githubusercontent.com/6304136/121826477-0b6f1000-cc75-11eb-9a5c-d1d36f2f33ba.png)

Is this for real? If so, I would say at least please restore it somehow. There were some really useful threads in there and now all is lost :( there's also no way to get the binaries anymore. Please restore them or upload them to mirrors. Thanks.

**Comment by laetemn** [comment]
ALL files...

http://pcem-emulator.co.uk/files/

**Comment by laetemn** [comment]
ALL files...

http://pcem-emulator.co.uk/files/

**Comment by mirrornoir** [comment]
It seems the lead developer posted this on the forums a couple days before this. It is a lot of effort to maintain a project like this so I don't blame her at all after reading this:

> You may have noticed there's been extremely little activity since the v17 release back in December. This isn't a sign of super secret dev work I'm afraid. I've been working on PCem for about 15 years now, and it's hard to keep enthusiastic about any one project that long. With the addition of Pentium II and Voodoo Banshee emulation, v17 saw PCem hit my long term goals of what I wanted to do with the project; it would be nice if it was a bit faster, but ultimately I've done what I originally set out to do.

> I had considered just walking away, however if I did that now PCem would likely just wither away and die. So I'm staying around for now; there are bugs I'd ideally like to get fixed, and there are a few potentially interesting bits of hardware to implement. However, I want to really encourage more people to get involved with the project, and with the _running_ of the project, so that when I'm done I can hand it over to people I trust to keep it going."

That being said it would be nice to see the forums restored but I don't feel this is a hack at all, just a human being who's exhausted maintaining this wonderful but expansive project. Forums require regular maintenance as well. Just be patient and in the worst case look for forks in the future, but I very much hope developers will come forward to continue stewardship of this project.

**Comment by mirrornoir** [comment]
The main site is back up, with an official message from the lead developer saying that she's stepped down from the project: https://pcem-emulator.co.uk/index.html

I wish Sarah the best of luck in her future endeavors, however the forums are still down. So I'm hopeful someone will come foward to continue this project and restore the forums.

**Comment by justledbetter** [comment]
PCem is truly a wonderful piece of software, thanks for sticking with it as long as you did, Sarah!

**Comment by darkdarkdrag0n** [comment]
please bring back the forum even if it is locked to read only
or have it in full added to wayback machine website
that way every one can still get access to the helpfull info that was all ready there

**Comment by vadosnaprimer** [comment]
> or have it in full added to wayback machine website

Looks like it's been there all along:
https://web.archive.org/web/20210610203401/https://pcem-emulator.co.uk/phpBB3/

**Comment by darkdarkdrag0n** [comment]
have you tryed to go more than 1 page deep in to it on there 
a soon as you try ti go to the 2nd page of General you get nothing
same thing on page one as soon as you try to go in to any of the following threds as an example
General > Close PCem after Windows Shutdown
General > Windows 3.11 Networking
General > v17 released!

**Comment by Mal752** [comment]
I think it is childish to just shut down everything and block all access to useful information posted by other members. 

No doubt the project is a very good one and she's talented, but she's not the type to completely open up to constructive criticisms and suggestions. 

This is an open source project and everyone is free to contribute and alter the code, but she is very stubborn to changes unless she approves them herself. If she really wants to mould the program how she wants, she should have made it closed-source and call it a day. But no, she needed to keep it open because she needs help, but she doesn't want it to be altered beyond her vision of the program. 

Open source does not work this way.

I won't be surprised if she takes down this github page too because of comments she might not approve.

**Comment by pcem-maintainer** [comment]
Don't worry, pcem will keep being maintained by volunteers in github, following the open source spirit. But it's important to note that burnout is real and people have other interests in life. Sarah was the sole contributor of new features and that may slow down a lot or come to a full stop - every other contributor saw pcem as a secondary hobby and mainly helped with bugfixes and incremental improvements, so no one sees this changing.

I'm closing this issue since all I believe all questions have been answered, feel free to re-open if you believe otherwise.

**Comment by darkguy2008** [comment]
> Don't worry, pcem will keep being maintained by volunteers in github, following the open source spirit. But it's important to note that burnout is real and people have other interests in life. Sarah was the sole contributor of new features and that may slow down a lot or come to a full stop - every other contributor saw pcem as a secondary hobby and mainly helped with bugfixes and incremental improvements, so no one sees this changing.
> 
> I'm closing this issue since all I believe all questions have been answered, feel free to re-open if you believe otherwise.

Yeah burnout definitely exist, any developer may have experienced it more than once in their lifee most likely, but one thing is just stopping development, and another one take down the main site - or even worse - the discussion forum with lots of useful stuff in there.

For instance, I'm coming back here to reply because I'm looking for info related to some issues running VMs in either PCem or _that other emulator_ , and some links go to the PCem forum which, to no surprise, get redirected to the homepage where it says she's done with it.

So I feel frustrated now because now I have to go through Google's cache which may not have the complete thread just because the owner got tired of it and couldn't think of something more mature to do instead.

All cool with PCem being taken over by other devs, but what about the forum? If the problem was due to some drama there then just delete the threads, do a purge, lock new signups and at least keep it open to browse for both the web history and the project documentation's sake. Now we lost a lot of useful info / workarounds / etc. related the project just for a naive attitude.

Sorry I'm also writing this out of frustration, but I think it's also fair to feel like this and to ask for the new plans for the info that was already lost in this act of immaturity?

**Comment by darkdarkdrag0n** [comment]
i agree with you darkguy2008 
basicly with out the forum it is a death blow to pcem
it will eventualy have intrest lost due to ppl geting anoyed about little things that previously has soloutions to listed in the forum
and over time it wont even show up in searches any more due to ppl giving up becouse of the loss of all the helpfull info that was in the forum

agian as posted above why couldnt the forum had been locked to read only mode after all it is a phbb i know for a fact it supports doing that
in read only mode no one except the admin can post a message and if there was more than 1 admin then simply Revoke all except the lead admin
if it was due to a DMCA or lawsuit problem the just say so and remove only the ofending content

but as stated above weather it was due to im maturity or just layzyness or carelesness this is a major loss to the pcem comunity

hell could have even asked if there was any one out there willing to take over hosting the forum
and by the way yes im offering to hoast a backup of the forum i have a server in my home that is on and online 24\7
im willing to host it even if it comes with a stipulation of read only mode or even if i have to moderate it by my self im offering my help to revive the forums info for the benifit of the comunity

**Comment by vadosnaprimer** [comment]
I agree that it would be a very helpful and wise idea to let someone else host the forum.

**Comment by Olddantrucker** [comment]
This is what happened to Cyberflix where the main person in charge had in fights with the team and eventually committed suicide.

**Comment by leilei-** [comment]
Forums are not trivial to maintain.  They can be a source of anxiety and stress (especially for an emulator where there's constant pressure and the events that lead to this).  I'm with Sarah on having them shut off.

**Comment by leilei-** [comment]
also a lot of the resolved solutions in the PCem problem threads tend to be about real behavior on PCs that's often forgotten about :)

**Comment by darkguy2008** [comment]
> Forums are not trivial to maintain. They can be a source of anxiety and stress (especially for an emulator where there's constant pressure and the events that lead to this). I'm with Sarah on having them shut off.

With this I totally disagree. You know phpBB has an useful amazing feature (just like other forums) called _Moderators_ so you can actually have a couple or more that are people you trust and can help you take care of the forum as well and weed out the bad users and remove any _offensive_ comments, right? 

I've managed quite a few forums in the past way back to those free forum platforms and sometimes BBS too, so it's not like it was all on Sarah's shoulders by design, more like by choice (and a bad one, for her own mental health's sake IMO).

I still think that it was a very immature idea to just shut it off instead of just disabling signups and removing the offending comments and users. The rest of the useful information in there didn't have to be taken down just for a couple of offending threads/users.

> also a lot of the resolved solutions in the PCem problem threads tend to be about real behavior on PCs that's often forgotten about :)

I also disagree with this as well. While you have a valid point, the real issue here is that at least those issues were documented **somewhere** (i.e. thanks too Google Cache (because the forum was down...) I discovered that Win98 works better if you use the parallel port mouse with forced 60hz instead of the serial one which is too jerky). Taking the forum down also took other heaps of useful information down that now it's impossible to retrieve even with archive.org

I still think that the decision made with the forums wasn't the most mature one. I used to be a long-time PCem fan and user, but sadly now I have to resort to direct people to VOGONs and 86box because at least their documentation sources are still alive and working and hopefully won't get taken down because of some internal issues that weren't taken care of by a psychologist. Sorry to be harsh, but someone had to say it.

Agree to disagree, but other commenters here have proven my point. I just hope that at least there's a backup somewhere that someone who actually knows how to manage a forum can put online and keep it going for the project's sake. Otherwise, what's good of a project if the community and documentation around it was forced to disappear?

**Comment by Mal752** [comment]
It is indeed a very selfish, immature and heartless move by Sarah, disregarding all contributions by the forum users. 

Deleting everything also deletes Sarah's own posts which avoids scrutiny of her own posts for others to decide and see who is right and wrong.

**Comment by sarah-walker-pcem** [comment]
@darkguy2008 Are you volunteering to moderate the forum?

**Comment by darkguy2008** [comment]
> @darkguy2008 Are you volunteering to moderate the forum?

Well I've managed a few forums in the past as mentioned above, so it would be an honor, actually :)

Although the general guideline is to delegate such tasks to people which you have a good relationship with (that way the core values, morals, perspectives, etc. are at least aligned around the moderating team) and have some kind of soft skills to either keep the community happy or at least without drifting too much into useless / controversial offtopic, I wouldn't mind to lend a helping hand in regards of the forum itself, as it used to be a good source of documentation/ideas in the past, and PCem is still ongoing with active users so it'd be a shame for it to be down and all its info down forever.

While I understand that there were quite a few uncomfortable threads/comments in it, so I'd be happy to look at each thread & post to make sure it meets basic community guidelines where everyone is treated with respect :)

Moderating a forum can be a stressing task (and definitely not fun, yeah) for a single person (been there, too) so my best suggestion is to pick at least two or three people who'll be happy to help you with this task. Again as suggested above, if we weed out the conflicting users/threads and make sure no one goes crazy in the forum, and the project gets a new maintainer(s?) to keep the project ongoing, I think that could be a way to keep everyone happy **and** also preserve a good part of emulation history complete with forums and all, considering it is/was the only real PC emulator that used real ROMs and emulated things accurately, even more than QEMU when it comes to old PCs.

Others have also volunteered to keep the forum online in the comments above, so I think that most people here (including myself) are actually concerned/sad about the harsh decision made with the forum (I kinda understand, though I disagree from a long-time project's POV) and are actually worried that it won't be back online and that it's all been lost, just because of some arguements in a place where there's absolute control to just remove the comments/users/threads, ignore them and keep going - at least that's what I would do (and also had to do some years ago when I was managing the forum of a game I was developing).

This all is also fueled by the fact that most links in Google regarding PCem + <insert any issue with old software here> point to the forum since it was the only source of documentation aside from the homepage which only contained the most basic info, and now they all don't work, thus making users feel discouraged (it happened to me!) and think the project may have stopped being in development or taken down and end up using alternatives, which to be honest, while may have improved in emulation accuracy, it requires beefier hardware to keep up with the same performance that PCem has (plus I also liked the _integrated_ VM manager frontend that _others_ lack...)

That's my two cents. I'll be happy to help, yes :) but then again, it's your project so you have the last word. 

Thanks for your reply, Sarah! :)

**Comment by sarah-walker-pcem** [comment]
@darkguy2008 It's up to the new maintainer (@pcem-maintainer), but to me that sounds reasonable. I'll admit I'm surprised by how much discord (and how many personal attacks) taking the forums down has generated.

**Comment by darkguy2008** [comment]
> @darkguy2008 It's up to the new maintainer (@pcem-maintainer), but to me that sounds reasonable. I'll admit I'm surprised by how much discord (and how many personal attacks) taking the forums down has generated.

Alright, let's hope the best for whatever decision is taken onwards :) 

Well in my case, I don't usually edit my posts after a while, because well, if you read it, you read it. Editing them doesn't make it better after that, so I apologize for the harsh comments I made in my past comments above. I think most of us were talking from the perspective we got from either a few github issues here or reddit/facebook posts regarding what happened, but @Mal752 said something very true though: With the forum down it's pretty hard to check for ourselves who's right and wrong, as we only get rumors and/or maybe only one side of the coin. That doesn't help much 😅

Part of those comments were due to frustration, too. In my search for the issue I had with the mouse pointer there were at least 2 or 3 links that pointed to the forum with people using PCem and facing the same problem, so as an user who didn't participate at all in all that ruckus (an innocent, in this case) it feels as if the blame is on me too because the forum just disappeared, and not just the offenders, so it's natural to feel frustrated at that.

I appreciate you reading all the comments and opinions though, even though some of them might've been hard to. Let's hope it all ends well for everyone... And it's okay to take a break too (after a long time developing PCem, it's admirable) just please try not to treat everyone as guilty. This took me (and us, I guess) by surprise, too.

**Comment by Mal752** [comment]
For forum maintenance, I would also like to add that deleting posts should be discouraged. A thread should be locked instead, (if the thread is deemed to have strayed too far off into the so called offensive territory), to let everyone see what has been going on and let people decide for themselves on the events that led to the locking. 

Progressive deleting of posts just removes the evidence and only gives one side of the story.

**Comment by darkdarkdrag0n** [comment]
a simple solution all thow temparary is to bring back a backup of the forum and lock the entier forum to all user read only, and admin edit only and remove any posts that were inflamitory
granted there would be no way for any new info but at least theo old inf would be avalable
could bring it back like this for 6month or 1 year that should give the comunity and or a new matainer time to get it all arcived or backed up or even migrated to someware else 
but just leaving the forums gone like this will just simply kill pcem off compleatly over time due to lack of the helpfull info and that will as well discurage any new mateainers from takeing it on
all thow at this point it looks like that wont even be alowd it is looking like the goal is to kill off pcem

**Comment by Olddantrucker** [comment]
The phone idiots will be happy though.  Everything in the cloud. Most users just care about Xbox and gaming. They don’t understand the value of the older software and doing things offline where you actually owned something.  The marketing people have their heads up their ass.

Sent from Kyle Hill Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by LingKuja** [comment]
> The phone idiots will be happy though. Everything in the cloud. Most users just care about Xbox and gaming. They don’t understand the value of the older software and doing things offline where you actually owned something. The marketing people have their heads up their ass.
Yeah, this is so sad.
I wish her luck, she deserves some rest.
And I also with the community would get together to keep the project alive, at least to maintain it usable with bugfixes and so on.
