### ISSUE TITLE
Instruction (README.md) for Linux seems to be incorrect

### ISSUE THREAD

**Issue by kedziorm** [sarah-walker-pcem/pcem#34]
Instruction contains following part:

> 
> ## BSD and Linux supplement (v17)
> 
> You will need the following libraries (and their dependencies):
> - SDL2
> - wxWidgets 3.x
> - OpenAL
> 
> Open a terminal window, navigate to the PCem directory then enter:
> ### Linux
> ```
> ./configure --enable-release
> make
> ```

However, running configure with such option, gives me:

```
configure: WARNING: unrecognized options: --enable-release
```

so I rather need to run:

```
./configure --enable-release-build --enable-alsa
```

for Linux.

It also seems that I needed to install also an ALSA library, as follows.

```
sudo apt-get install build-essential libsdl2-dev libgtk2.0-dev libgtk-3-dev libopenal-dev libasound2 libwxgtk3.0-gtk3*
```

Could we add it as an example command for installation in Linux?

**Comment by pcem-maintainer** [comment]
Your example command to install the dependencies seems to be missing the wxWidgets library, can you please let me know the correct package name under Debian/Ubuntu?

**Comment by kedziorm** [comment]
Thank you for verification.
I added `libwxgtk3.0-gtk3*` into my command

**Comment by michael-manley** [comment]
The README has vastly changed when I became maintainer.
It is now using CMake so the parameters changed.

Honestly I don't want to add commands for packages to the README as depending on your distro they may be different. And ALSA is only needed if you actually do -DUSE_ALSA=ON if you don't, you can omit ALSA which is default.

I believe this issue can be closed, but I will add a comment about if you use ALSA mode you will also need that dependency.
