### ISSUE TITLE
Sarah, please mint the PCem source code as an NFT and allow us to pay you back a little 🙂

### ISSUE THREAD

**Issue by volkertb** [sarah-walker-pcem/pcem#35]
@sarah-walker-pcem THANK YOU for so many years of unpaid work on PCem, and for sharing it with the world. :relaxed:

Would it be an idea for you to mint the source code, in the state as it was when you handed its stewardship over to the community (the initial GitHub commit?), as an NFT, so you can earn a little well-deserved (virtual) coin from it? It might be a silly idea, and I'm not sure how much (if anything) it would earn you in practice, but perhaps it would be an opportunity for the community to repay you. And it would also create kind of a monument to your work.

If you are concerned about the environmental aspect of NFTs, it could be minted on Tezos, which is (supposedly) much more environmentally friendly than Ethereum (as long as they haven't migrated to Proof-of-Stake yet).

Disclaimer: I have zero experience with NFTs myself, but perhaps others here with more expertise could help you make this happen.

**Comment by Falcon2k1** [comment]
Donations would be a much better way to simply provide financial support to a dev you support, without getting into the inequality-fueled world of NFTs.

**Comment by volkertb** [comment]
Fair enough. It was a bit of a spontenous idea. :sweat_smile: I'll close this issue.
