### ISSUE TITLE
Unable to select network card

### ISSUE THREAD

**Issue by HeroponRikiBestest** [sarah-walker-pcem/pcem#37]
![image](https://user-images.githubusercontent.com/50224630/123525239-0f8f2a80-d684-11eb-997d-fe0c7bd7f964.png)
I've tried with various different machines, this network drop down menu is greyed out, so I cannot select any network card. I'm running pcem v17 on Linux mint 20. I'm likely just doing something very simple wrong, but I could not find any solution to this issue. Additionally, I made sure I have ne2000.rom at ~/pcem/roms/ne2000.

**Comment by leilei-** [comment]
Did you compile with --enable-networking?

**Comment by HeroponRikiBestest** [comment]
Trying to compile with --enable-networking just returns the "unrecognized option" text.

**Comment by HeroponRikiBestest** [comment]
Oh, I'm really stupid, I need to run ./configure with it. Sorry for the pointless issue. Closed.

Out of curiosity, though, why do you have to choose to enable networking? You still have to select a network card manually, so I can't imagine there's an extra security/privacy risk.

**Comment by pcem-maintainer** [comment]
IIRC, it was experimental ported code from other emulators, plus it added an optional dependency under Windows, so it's usual to have it as an compile-time option.
