### ISSUE TITLE
[AudioPCI/SB 128]: Distorted/crackling sound effects and no CD audio in Screamer series

### ISSUE THREAD

**Issue by unreal9010** [sarah-walker-pcem/pcem#48]
**Describe the bug**
Sound effects are a bit distorted in Screamer, Screamer 2 and Screamer Rally (as well as in many other games that I've tried) if running them with AudioPCI or SB 128 card. 
Using any Win9X driver version released between 1997 and 2001 for AudioPCI or SB 128 produces horrible sound effects in any of the first three Screamer games.  Although later drivers from 2000 onwards that support SB16 emulation no longer complain about an IRQ error upon starting the game, sound is equally distorted and no CD audio could be heard in Screamer 2/Rally.
I tried running the games from pure DOS mode and no difference in terms of sound effects. I watched the video on how Screamer Rally was suppossed to sound like on AudioPCI and as you can hear in the video the sound effects are not crackled or distrorted (see 2:52 - 3:16 in the video attached below). Switching mainboard, OS or disabling LPT interrupt sharing makes no difference either. 
Now I know AudioPCI-based cards aren't the best ones for DOS games, however given how many games I'v tried with similar issues so far I think that there are some bugs left in AudioPCI sound effects emulation. 

**To Reproduce**
1. Launch any of the Screamer games mentioned above
2. Hear distorted and crackling sound effects

**Expected behavior**
A clear and undistorted sound with CD audio music playing in the background. Like here:
https://www.youtube.com/watch?v=gJrrUYg2hsE

**Screenshots**

**Emulator configuration**
 - Machine: GA 686-BX
 - CPU: Pll 233
 - Graphics/sound cards: ViRGE/DX, SB 128
 - Windows 95

**Host machine**
 - OS: Windows 10
 - V 17
 - Core i7 6700

**Additional context**
https://www.youtube.com/watch?v=gJrrUYg2hsE

**Comment by okudayukiko** [comment]
Emulator configuration:
GA-686BX
Pentium II
Sound Blaster PCI
Voodoo 3 PCI
Windows ME
Also encountered this issue.

**Comment by unreal9010** [comment]
I set the buffer length to 400 ms, however, there is hardly any diference. Also encountered this issue in Quake and several other DOS games. Running them from Windows or pure DOS makes no difference.

**Comment by unreal9010** [comment]
Sound distortion fixed in my latest commit, still trying to figure out why CD audio volume gets lowered almost to zero.

**Comment by Tasosgemah** [comment]
I also can't make the CD audio to work in this game, instead the midi music is playing. I don't know how to change it to the CD audio, low volume or not. There is no option for this anywhere.

**Comment by unreal9010** [comment]
This is due to a bug in PCem's CD audio emulation. CD audio is actually present, however, you need to push the volume VEEERY high to be able to hear it (and only barely). Switching to SB16 made no difference either, meaning it's not a SB128 bug like I previously assumed. However, I tried the game with certain PCem fork and CD audio worked normally as it should.
What's also interesting is that if you run the game from Windows, all further CD images that you mount under PCem will have CD audio almost completely silenced until the next system reboot.

**Comment by Tasosgemah** [comment]
> CD audio is actually present, however, you need to push the volume VEEERY high to be able to hear it (and only barely).

Seems not the case for me. I don't have CD audio in this game _at all._ And because of this all i get is the midi version of the songs. I have no idea how am i supposed to change to CD audio, even if it's barely audible.

**Comment by unreal9010** [comment]
Open the Screamer 1 folder and run setup.exe. Select "CD ROM" as your music card. Screamer 2 and Screamer Rally don't support MIDI music. Only CD Audio.

**Comment by Tasosgemah** [comment]
Ok i did that and the music worked in the setup application after i tested it.

But in-game there's no music. Not even barely audibly.

I'm not even surprised though, CD music doesn't work half of the time in many games with PCem anyway.

**Comment by unreal9010** [comment]
Yes, as mentioned earlier, there are issues with CD audio emulation in PCem. I couldn't hear the music in dozens of games that  use CD audio that I tried (both Windows/DOS titles under any sound card) either. For now, the solution is to play these games without being able to hear the music or use any of the PCem forks where such issues have already been fixed.

**Comment by unreal9010** [comment]
What's interesting, though, is that in games where CD audio does work it's usually twice as loud as the sound effects. Same also goes for MIDI, at least with SB128 and other AudioPCI-based sound cards. In Screamer 1, for example, MIDI music is about 2-3 times louder than sound effects.

**Comment by Tasosgemah** [comment]
SB16 is the opposite for me. If the CD audio works (like in Quake sometimes) the volume is very low even at max setting and i have to push down the SFX below 50% to balance it.

MIDI seems OK i think.

**Comment by unreal9010** [comment]
What I also found out is that after I quit Screamer 2 and return to Windows 95 desktop, CD audio music becomes (almost) inaudible regardless of which image file I use with PCem until the next Win 95 system reboot. I attempted to play Screamer 2 disc through Windows 95 CD player right after I quit the game and I had to reboot Windows in order to be able to hear anything.

**Comment by unreal9010** [comment]
Changing CD volume level in DOS and Windows had no effect. Neither did switching between various sound output level in PCem. Looks like a sound volume-related issue. The levels drop down to (almost) zero when they shouldn't and in certain other examples go way up high.
