### ISSUE TITLE
Donation Link in README

### ISSUE THREAD

**Issue by samuelpismel** [sarah-walker-pcem/pcem#49]
Hey guys, what about a donation link in the readme? 

Would be great to support this project!

**Comment by tlewis23** [comment]
The dev abandoned the project. But if you want to waste your money, then go for it.

**Comment by circl-lastname** [comment]
Anybody know why did the dev abandon it, why would they close the forum and throw out a lot of resources, and who's currently maintaining this project?

**Comment by tlewis23** [comment]
She threw a temper tantrum whenever anyone questioned or suggested anything. Supposedly someone was going to pick up and maintain but nothing has happened yet.

**Comment by sarah-walker-pcem** [comment]
In other words you can't answer the question. So why bother replying?

Closing this as it really serves no purpose at all other than to slander me.

**Comment by tlewis23** [comment]
See what I mean?

**Comment by sarah-walker-pcem** [comment]
No?

**Comment by circl-lastname** [comment]
Well maybe if you kept the forum open we wouldn't be discussing it here

**Comment by samuelpismel** [comment]
Hey, Sarah, sorry about all that... I don't know the motivation to close the project, but I want to thank you for all your effort on it.
You must to be a really nice person to give to the world something great like this. :smiley: 

I wish you the best!
