### ISSUE TITLE
Created a situation where opening the right-click menu causes an assert failure

### ISSUE THREAD

**Issue by HeroponRikiBestest** [sarah-walker-pcem/pcem#50]
**Describe the bug**
I have created a situation where PCEM freezes, and if I try and open the right-click menu, an assert failure is triggered.

**To Reproduce**
From attached Hard Drive image:
- Boot windows 95 as normal
- The boot sequence detects 2 files as corrupt, get past the boot sequence in whatever way possible (I found that hitting D and then F got past the first file that fails, I believe the same worked for the second file)
- Once windows 95 has booted, open C: Screamocity in the file explorer, and open DIR00002
- After a second, the emulation will freeze. Trying to open the right click menu now will cause this assert failure.

**Expected behavior**
I expected the right click menu to open as normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/50224630/128558201-a62dbc8c-a517-4e2b-8566-d012d478d2e7.png)

**Emulator configuration**
 - Machine: [Socket 7] Shuttle HOT-557
 - CPU: Intel Pentium 100/50
 - Graphics/sound cards: Phoenix S3 Trio32, Sound Blaster AWE32
 - Installed OS: Windows 95
 Additional specs:
 128MB memory, Novell NE2000.

**Host machine**
 - OS: Linux Mint 20.2
 - Emulator version v17 (Built 2 days ago)

**Additional context**
I'm sorry if this isn't an actual bug; I assumed it was, since the error was delivered through a PCEM debug window and not W95 itself.
I have attached my hard drive image to this bug report because, as far as I know, there is no copyrighted content within it, and I would not be able to reproduce the creation of this hard drive image. The only 2 things of note on it are the shareware demo of slickball, and patches for a game called YU-NO (but no files from the actual game itself). If this hard drive image is still not acceptable to be uploaded here, I will delete the link.
*removed*
In case you're wondering roughly how I created this hard drive image:
- I mounted the disk image in Linux Mint and copied the YUNO music patch folder into it
- I booted into Windows 95 and tried to copy the folder within Windows to make the hard disk image bigger, so I could put more files into the disk image while mounted in Mint
- About 1/3 through the installation, emulation speed slowed to 0-2%, despite none of my threads being anywhere close to maxed, and the emulator always running at fullspeed before this
- I quit emulation and then tried to restart it
(I'm aware there's a lot of things wrong with that process and it's a terrible way to go about putting files in; I just thought a description of how I got here could help).
Again, sorry if this is a waste of time.

**Comment by sarah-walker-pcem** [comment]
> I have attached my hard drive image to this bug report because, as far as I know, there is no copyrighted content within it

Windows 95 is copyrighted content.

**Comment by HeroponRikiBestest** [comment]
Ah, right, sorry. There's no way for me to recreate this issue without the hard drive image, so I'll just close the issue.
