### ISSUE TITLE
Emulation menu not working on Ubuntu 21.04

### ISSUE THREAD

**Issue by davidfriscia** [sarah-walker-pcem/pcem#58]
While emulation is running and the mouse is not captured, right button click on the main area don't display the menu.

1. Build PCEM v17 on Ubuntu 21.04
2. Run the application and define a new configuration
3. Start the emulation
4. Right mouse button click on the main window area

The click should display the menu but nothing happen

This behaviour appen with any emulator configuration

Host machine: Ubuntu 21.04 and PCEM 17

I compiled the software on a Debian 11 (Mate Desktop) running on qemu and everithing work ok.

**Comment by michael-manley** [comment]
I think I seen this issue myself when I was running 21.10 but I am now running 20.04 on my main PC.

I'll throw up an 21.10 VM and figure out why. I also noticed some weird wxWidgets issues on 21.10 as well where sometimes the dialogs get cropped on my dev build.

**Comment by shankao** [comment]
Both Ubuntu 21.04 and 21.10 have reached end of life support.
I'm currently using pcem built from source on 22.04 and it doesn't show this problem.
