### ISSUE TITLE
PCem Maintainership

### ISSUE THREAD

**Issue by michael-manley** [sarah-walker-pcem/pcem#63]
Hello to whom it may concern,

I saw that this project is no longer being maintained and the forums are locked out. I am willing to take over any of the maintainership of those and host on my servers so that the knowledge will not be lost and to continue development. I totally understand burn-out but it be such a shame to loose all that history.

Feel free to reply to this or email me at mjmanley@ntge.net to discuss this further.

**Comment by MrMe85** [comment]
Just as a comment, I hope that this project can be maintained and continued in some shape or form.  PCem is an amazing piece of software and is still my favorite when it comes to low level emulation of older PCs with features I prefer over some its forks.  I'd hate to see it disappear or become obsolete.  While I can only wish the original dev (Sarah) would come back and continue to work on it, I do hope that in the alternative, you are able to take over maintainership and continue its development.  All the best.

**Comment by michael-manley** [comment]
I did also send an email to her, but yet to get a response. Hopefully soon as I already started development and any bug-fixing. Just finished some refactoring.

I am going to mirror the code to github soon to allow pull requests back but it is at https://code.ntge.net/pcem/pcem but so far only refactoring work has been done. Just to tidy up src and whatnot. More to come though

**Comment by MrMe85** [comment]
Keep up the good work.  Look forward to seeing how it progresses.

**Comment by unreal9010** [comment]
Try contacting the author on VOGONS forum if there will be no response. Also, make sure that you do not upload or share any copyrighted rom files such as BIOSes. The author has a strict policy of not uploading or sharing any of these.
I'm glad to see that things are finally moving.

**Comment by michael-manley** [comment]
Just an update, I am in contact with Sarah and working on a plan as we speak.

I moved my changes to GitHub under my account in preparation (aka a easy going merge request). This repo will be the repo code will be pushed to. No need to start confusing existing developers :)

Can't wait to get everything going and show whats in store for PCem, but it will be great!

**Comment by unreal9010** [comment]
Excellent, keep up the good work.

**Comment by leilei-** [comment]
Looking forward to this!

**Comment by sarah-walker-pcem** [comment]
I think this can be closed now :)
