### ISSUE TITLE
Discussing cmake issues/workarounds

### ISSUE THREAD

**Issue by shermp** [sarah-walker-pcem/pcem#72]
I've just managed to compile PCem with CMAKE, and I thought I'd provide some feedback and workarounds here.

First, the MSYS2 projects recommend the Ninja generator. The only thing I had to do to get this to work is add `-DMSYS=TRUE` to the argument list. Setting this option forces findwxwidgets.cmake to use `wx-config` instead of having to specify file paths.

If networking is enabled, you should probably also check for required dependencies (pcap) as well.

**Comment by michael-manley** [comment]
Thanks for the information, i did update the package dependencies on the windows docs. I develop in Linux by default and test Windows after, so I tend to miss these little nuances till GitHub does a build.

I tend to just use Make, but good to know if you want to use Ninja you just do -DMSYS=TRUE to get around the annoying findwxwidgets issues.

**Comment by shermp** [comment]
Yeah, that wxWidgets issue is a PITA. It should really just check if `wx-config` is available regardless of platform, and only fall back to user supplied paths if required, but no, it will not even attempt `wx-config` if windows and not msys.

**Comment by jviskari** [comment]
I have clean install of the MSYS and MinGW64. 

cmake -G "Ninja" -DMSYS=TRUE -DCMAKE_PREFIX_PATH=/mingw64 ..

results this error:
CMake Error at /usr/share/cmake-3.22.1/Modules/FindwxWidgets.cmake:989 (message):
  wxWidgets wx/version.h file not found in
  C;/msys64/mingw64/lib/wx/include/msw-unicode-3.0;C;/msys64/mingw64/include/wx-3.0.
Call Stack (most recent call first):
  CMakeLists.txt:93 (find_package)

I also installed the required packages with pacman

            base-devel
            zip
            unzip
            mingw-w64-x86_64-ntldd-git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-openal
            mingw-w64-x86_64-wxWidgets
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-libpcap
            mingw-w64-x86_64-ninja
 
 Did I miss some obvious step in the installation process?

**Comment by shermp** [comment]
Ensure you are in the mingw64 shell (not MSYS shell), and you shouldn't need `-DCMAKE_PREFIX_PATH=/mingw64`. Being in the correct shell ensures all paths are set correctly.

**Comment by michael-manley** [comment]
I found out how to use CMake without needing the MSYS/MinGW Shell
[gccvars.zip](https://github.com/sarah-walker-pcem/pcem/files/8478065/gccvars.zip)

Attached is some scripts that add /usr/bin and /mingwXX/bin to the Windows path. Doing this has wx-config called correctly.

You do still need -DMSYS=TRUE

Will add to Wiki in time.

Closing as this fixes remaining issues with CMake
