### ISSUE TITLE
PCEM Crashes from Address boundary error

### ISSUE THREAD

**Issue by Alee14** [sarah-walker-pcem/pcem#73]
**Describe the bug**
PCEM crashes after sometime using the desktop

**To Reproduce**
1. Open my Windows 98 VM
2. Login into the desktop
3. PCEM crashes

**Expected behavior**
PCEM just crashes after booting into the desktop

**Screenshots**
```
❯ pcem
Set fullspeed - 0 0 0
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)

(pcem:1439603): Gtk-WARNING **: 21:30:07.452: Unable to locate theme engine in module_path: "adwaita",
Menu item not found: 1403
Menu item not found: 1404
ALSA lib rawmidi_hw.c:352:(snd_rawmidi_hw_open) open /dev/snd/midiC0D0 failed: No such file or directory
Menu item not found: 1403
Menu item not found: 1404
fish: Job 1, 'pcem' terminated by signal SIGSEGV (Address boundary error)
```

**Emulator configuration**
 - Machine: [Socket 7] Shuttle HOT-557
 - CPU: Intel Pentium 200
 - Graphics/sound cards: S3 ViRGE/DX + Voodoo 2/Soundblaster AWE32
 - Installed OS: Windows 98

**Host machine**
 - OS: Arch Linux
 - Emulator version PCEM 17 (AUR Version)
 - Any other relevant information

**Additional context**

**Comment by michael-manley** [comment]
Out of curiosity, does this happen if you use a different video card instead of the S3 ViRGE? I have been noticing some segfaults with that card emulation on dev, but usually only on emulation close.

**Comment by Alee14** [comment]
I have used 

> Out of curiosity, does this happen if you use a different video card instead of the S3 ViRGE? I have been noticing some segfaults with that card emulation on dev, but usually only on emulation close.

I have used a different video card, same affect
