### ISSUE TITLE
Mouse release shortcut (CTRL+END) broken.

### ISSUE THREAD

**Issue by paulguy** [sarah-walker-pcem/pcem#89]
**Describe the bug**
Since a system update a few days ago on Arch linux (could be some other cause but that's all I could think of), the mouse release shortcut stopped working.

**To Reproduce**
Start emulation, click the screen to capture the mouse, press CTRL+END to release the mouse.

**Expected behavior**
Mouse arrow is released.

**Screenshots**
n/a

**Emulator configuration**
various

**Host machine**
OS: Arch Linux (SDL2 2.0.18-3)
PCem: tried v17, master (dev doesn't run)

**Additional context**
I have a patch which fixes the problem, but it wouldn't merge with dev because a bunch of stuff has moved around and I can't run the dev version to test against it, but the change should be similar.  Otherwise, I would've tried a pull request.
```
diff --git a/src/wx-sdl2-display.c b/src/wx-sdl2-display.c
index ac8c23e..2123356 100644
--- a/src/wx-sdl2-display.c
+++ b/src/wx-sdl2-display.c
@@ -559,7 +559,7 @@ int render()
                 trigger_screenshot = 0;
                 take_screenshot = 1;
         }
-        else if ((event.key.keysym.scancode == SDL_SCANCODE_END || event.key.keysym.scancode == SDL_SCANCODE_KP_1) &&
+        else if ((rawinputkey[sdl_scancode(SDL_SCANCODE_END)] || rawinputkey[sdl_scancode(SDL_SCANCODE_KP_1)]) &&
                         (rawinputkey[sdl_scancode(SDL_SCANCODE_LCTRL)] || rawinputkey[sdl_scancode(SDL_SCANCODE_RCTRL)]))
                 trigger_inputrelease = 1;
         else if (trigger_inputrelease)
```
I don't know why this fixes it but it was the shortcut that wasn't working that also was checking the scancode directly while the others weren't so I tried changing it to be like the others and it started working again.

**Comment by michael-manley** [comment]
I added this to dev to resolve the issue with the mouse not releasing.

May I ask, since I use openSUSE, what is not working in Arch on dev, since you said dev does not run and you are using Arch.

**Comment by paulguy** [comment]
It crashes when I start an emulated system and with some testing it seems to crash for any CPU option greater than a 486 when built for Release.  Usefully, doesn't crash when built for Debug, but here's the incomplete call stack.  I've tried the Shuttle HOT-557 and the Gigabyte GA-686BX.  Also discovered that choosing any PS/2 model just crashes right after hitting OK on the configuration window.  I could open these as separate bugs if that makes tracking these issues easier.
```
Thread 40 "Main Thread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff777fe640 (LWP 333836)]
0x00007ffff60284c6 in exec386_dynarec () from /home/paul/pcem/pcem/output/lib/libpcem.so
(gdb) bt
#0  0x00007ffff60284c6 in exec386_dynarec () at /home/paul/pcem/pcem/output/lib/libpcem.so
#1  0x00007ffff620ff1d in runpc () at /home/paul/pcem/pcem/output/lib/libpcem.so
#2  0x00007ffff625c689 in mainthread () at /home/paul/pcem/pcem/output/lib/libpcem.so
#3  0x00007ffff533ca39 in  () at /usr/lib/libSDL2-2.0.so.0
#4  0x00007ffff4ec0259 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007ffff4de75e3 in clone () at /usr/lib/libc.so.6
```

**Comment by michael-manley** [comment]
I will add to a separate ticket, but I need to figure out why, but somehow a variable is being optimized out, had to make a RelWithDebInfo build to find it. But I did just force that function to be ignored by optimizations. This seems to resolve the dynarec crash.

The one on selecting a PS/2 has to do with a NULL Check I forgot. I also fixed that as well. It will be on the latest commit.

**Comment by michael-manley** [comment]
If you want to follow the issue in depth, its Issue #92. This issue is fixed.
