### ISSUE TITLE
GA-686BX: PCem crashes when using BIOS files released before 2000

### ISSUE THREAD

**Issue by unreal9010** [sarah-walker-pcem/pcem#9]
**Describe the bug**
When using any GA-686BX BIOS file released before 2000, PCem always crashes during one of the last sections of the Windows 95 (or 98SE) installation procedure, in particularly at the point when the installer is about to install the Windows help file (this comes after the P'N'P devices configuration section is complete). The only workaround this issue is to use any BIOS file released from 2000 onwards. Switching back to an older version makes the issue reappear. 
I did a little experiment by copying HD file of another emulated machine and while I could normally boot into Windows using any 2000 or 2001 BIOS file I had no such luck with any 1998 or 1999 version I tried as PCem would crash during Windows boot screen. Happens with both Windows 95 and 98. 

**To Reproduce**
1. Use any BIOS file dated 1998 or 1999 instead of your regular one (likely the 2001 one).
2. Start your virtual machine.
3. Wait for PCem to crash not long after the Windows boot screen shows up.

**Expected behavior**
Normal bootup and completable installation proceedure of Windows. 

**Screenshots**

**Emulator configuration**
 - Machine: GA-686BX
 - CPU: Pentium ll 233
 - Graphics/sound cards: Voodoo Banshee,3,Virge/DX/SB 128
 - Windows 95,98SE

**Host machine**
 - OS: Windows 10
 - PCem v17
 - i7 6700 @ stock speed

**Additional context**

**Comment by sarah-walker-pcem** [comment]
Should be fixed by commit be74288b.

**Comment by unreal9010** [comment]
It is indeed fixed. Thank you.
