### ISSUE TITLE
Commodore SL386SX-25 hardware EMS driver error

### ISSUE THREAD

**Issue by Fenix770** [sarah-walker-pcem/pcem#98]
**Describe the bug**

Two years have passed since this machine was added, however, I finally found the correct hardware EMS driver for the SCAMP chipset. The hardware EMS driver detects the chip, but finds errors on all EMS memory pages.
The UMB_DRVR software driver to create UMB memory crash after detecting the chip too.
I know I can use EMM386 to create EMS memory. But I'd like to test the hardware EMS capabities (and once it is emulated, maybe sometime in the future will be, also, possible to add 286 based SCAMP chipset to add EMS memory support to these 286.)

(I uploaded the VLEMM.SYS driver only on a floppy disk image, because this is very hard to find on the web. _I know all other software is may have copyright_)

Here is the floppy image:
[VLSI 82C311 EMS driver.zip](https://github.com/sarah-walker-pcem/pcem/files/7937071/VLSI.82C311.EMS.driver.zip)

*To Reproduce**
1. Start the Machine
2. Add the VLEMM.SYS driver to the CONFIG.SYS file
3. Boot the machine
4. The EMS driver finds errors on all EMS memory pages.

**Expected behavior**

**Screenshots**
![imagen](https://user-images.githubusercontent.com/31600563/151057940-4583f908-1743-4731-b8c6-5442d0d0c491.png)
![imagen](https://user-images.githubusercontent.com/31600563/151058003-3eba9107-3afd-4c7d-84e1-22615aed80aa.png)

**Emulator configuration**
 - Machine: Commdore SL386SX-25
 - CPU: 386 SX/25
 - Graphics/sound cards: on-board AVGA 2 
 - Installed OS: DOS + Windows 3.1

**Host machine**
 - OS: Windows 10 21H2 
 - Emulator version PCem v17
 - Any other relevant information

**Additional context**

**Comment by sarah-walker-pcem** [comment]
Fixed as of https://github.com/sarah-walker-pcem/pcem/commit/464376db374c9ddaf3dde231157326658000ee76.
