### ISSUE TITLE
Superficial emulation of IDE IDENTIFY DEVICE request prevents WinCE7 from booting

### ISSUE THREAD

**Issue by Stein2051** [sarah-walker-pcem/pcem#99]
Currently PCEm returns 0 in IDENTIFY_DEVICE_DATA.GeneralConfiguration (ide->buffer[0]).
It makes the wince ide driver to freeze on the early initialization stage with diagnosis "Atapi!CDisk::Identify> General configuration(0000) not valid; device not present".

The relevant check is in ./public/common/oak/drivers/block/atapi/diskmain.cpp:
    // Validate IDENTIFY DEVICE/IDENTIFY PACKET DEVICE signature; an empty
    // channel may return invalid data.
    if ((m_Id.GeneralConfiguration == 0) || (m_Id.GeneralConfiguration == 0xffff) || (m_Id.GeneralConfiguration == 0xff7f) || (m_Id.GeneralConfiguration == 0x7fff) || ((m_Id.GeneralConfiguration == m_Id.IntegrityWord) && (m_Id.NumberOfCurrentCylinders == m_Id.IntegrityWord))) { ...

Adding one-liner to ./ide/ide.c::ide_identify() seems to resolve the problem -- booting continues, and the system becames workable:
	ide->buffer[0] = 0x0040; /* GeneralConfiguration.FixedDevice = 1 */

**Comment by sarah-walker-pcem** [comment]
Fixed at https://github.com/sarah-walker-pcem/pcem/commit/1bf273a09ce8cac0f27a67f3977689db4c34c069
